#!/usr/bin/env python3
"""Convert graphics/custom/backgrounds/*.png to 8bpp AT4PN + pal for friend-area intros.

Output next to each PNG:
  <slug>.at4pn  — AT4PN: 2×32×32 tilemaps + 8bpp tiles
  <slug>.pal    — 240 RGBX colors (index 0 reserved transparent)

Also regenerates src/friend_area_intros_data.c (INCBINs + ID→asset table).

Same VRAM layout as custom title backgrounds (BG3 8bpp, max 600 tiles).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from PIL import Image

import convert_title_backgrounds as title

ROOT = Path(__file__).resolve().parent
SRC_DIR = ROOT / "graphics" / "custom" / "backgrounds"
GEN_C = ROOT / "src" / "friend_area_intros_data.c"

# Friend area ID → PNG slug (FRIEND_AREA_NONE = 0 has no art).
# Most match the constant suffix; four filenames diverge from the ID name.
FRIEND_AREA_SLUGS: list[tuple[int, str]] = [
    (1, "bountiful_sea"),
    (2, "treasure_sea"),
    (3, "serene_sea"),
    (4, "deep_sea_floor"),
    (5, "deep_sea_current"),
    (6, "seafloor_cave"),
    (7, "shallow_beach"),
    (8, "mt_deep_green"),  # FRIEND_AREA_MT_DEEPGREEN
    (9, "mt_cleft"),
    (10, "mt_moonview"),
    (11, "rainbow_peak"),
    (12, "wild_plains"),
    (13, "beau_plains"),
    (14, "sky_blue_plains"),
    (15, "safari"),
    (16, "scorched_plains"),
    (17, "sacred_field"),
    (18, "mist_rise_forest"),
    (19, "flyaway_forest"),
    (20, "overgrown_forest"),
    (21, "energetic_forest"),
    (22, "mushroom_forest"),
    (23, "healing_forest"),
    (24, "evolution_forest"),  # FRIEND_AREA_TRANSFORM_FOREST
    (25, "secretive_forest"),
    (26, "rub_a_dub_river"),
    (27, "tadpole_pond"),
    (28, "turtle_shell_pond"),  # FRIEND_AREA_TURTLESHELL_POND
    (29, "mystic_lake"),
    (30, "waterfall_lake"),
    (31, "peanut_swamp"),
    (32, "poison_swamp"),
    (33, "echo_cave"),
    (34, "cryptic_cave"),
    (35, "dragon_cave"),
    (36, "boulder_cave"),
    (37, "jungle"),
    (38, "decrepit_lab"),
    (39, "mt_discipline"),
    (40, "thunder_meadow"),
    (41, "power_plant"),
    (42, "crater"),
    (43, "furnace_desert"),
    (44, "aged_chamber_an"),
    (45, "aged_chamber_unknown_o"),  # FRIEND_AREA_AGED_CHAMBER_O_EXCLAIM
    (46, "ancient_relic"),
    (47, "darkness_ridge"),
    (48, "frigid_cavern"),
    (49, "ice_floe_beach"),
    (50, "volcanic_pit"),
    (51, "stratos_lookout"),
    (52, "ravaged_field"),
    (53, "magnetic_quarry"),
    (54, "legendary_island"),
    (55, "southern_island"),
    (56, "enclosed_island"),
    (57, "final_island"),
]


def convert_one(png: Path, force: bool = False) -> bool:
    out_at = png.with_suffix(".at4pn")
    out_pal = png.with_suffix(".pal")
    if (
        not force
        and out_at.exists()
        and out_pal.exists()
        and out_at.stat().st_mtime >= png.stat().st_mtime
        and out_pal.stat().st_mtime >= png.stat().st_mtime
    ):
        return False

    im = title.flatten_rgb(Image.open(png))
    raw, pal, ntiles, ncolors, merged = title.convert_image(im)
    out_at.write_bytes(title.wrap_at4pn(raw))
    out_pal.write_bytes(pal)
    extra = ", merged" if merged else ""
    print(
        f"  {png.name}: colors={ncolors}, tiles={ntiles}{extra}, "
        f"at4pn={out_at.stat().st_size}"
    )
    return True


def slug_to_c_ident(slug: str) -> str:
    parts = slug.split("_")
    return "gFriendAreaIntro" + "".join(p[:1].upper() + p[1:] for p in parts)


def generate_c() -> None:
    lines = [
        '#include "global.h"',
        '#include "friend_area_intros.h"',
        '#include "constants/friend_area.h"',
        "",
        "/* Generated by convert_friend_area_backgrounds.py — do not edit. */",
        "",
    ]

    for _area_id, slug in FRIEND_AREA_SLUGS:
        ident = slug_to_c_ident(slug)
        base = f"graphics/custom/backgrounds/{slug}"
        lines.append(f"static const u8 {ident}Gfx[] = INCBIN_U8(\"{base}.at4pn\");")
        lines.append(f"static const u8 {ident}Pal[] = INCBIN_U8(\"{base}.pal\");")

    lines.append("")
    lines.append("const FriendAreaIntroAssets gFriendAreaIntroAssets[FRIEND_AREA_COUNT] = {")
    lines.append("    [FRIEND_AREA_NONE] = { NULL, NULL },")
    for area_id, slug in FRIEND_AREA_SLUGS:
        ident = slug_to_c_ident(slug)
        lines.append(f"    [{area_id}] = {{ {ident}Gfx, {ident}Pal }},")
    lines.append("};")
    lines.append("")

    GEN_C.write_text("\n".join(lines))
    print(f"wrote {GEN_C.relative_to(ROOT)}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--stamp", type=Path, default=None)
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    missing = []
    for _area_id, slug in FRIEND_AREA_SLUGS:
        png = SRC_DIR / f"{slug}.png"
        if not png.is_file():
            missing.append(slug)
    if missing:
        print(f"error: missing PNGs: {', '.join(missing)}", file=sys.stderr)
        return 1

    if not args.quiet:
        print(f"Converting {len(FRIEND_AREA_SLUGS)} friend-area backgrounds...")

    changed = False
    for _area_id, slug in FRIEND_AREA_SLUGS:
        png = SRC_DIR / f"{slug}.png"
        if convert_one(png, force=args.force):
            changed = True
        elif not args.quiet:
            print(f"  {png.name}: up to date")

    generate_c()
    changed = True  # data.c always rewritten for a stable stamp dependency

    if args.stamp is not None:
        args.stamp.parent.mkdir(parents=True, exist_ok=True)
        args.stamp.write_text("ok\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
