#ifndef GUARD_CONSTANTS_DUNGEON_MODIFIERS_H
#define GUARD_CONSTANTS_DUNGEON_MODIFIERS_H

enum FloorModifier {
    FLOOR_MODIFIER_NONE = 0,
    FLOOR_MODIFIER_POISONOUS_AIR,
    FLOOR_MODIFIER_DARKNESS,
    FLOOR_MODIFIER_ELECTRIC_TERRAIN,
    FLOOR_MODIFIER_TREASURE_RICH,
    FLOOR_MODIFIER_COUNT,
};

#define FLOOR_MODIFIER_CHANCE 20 /* Percent chance a floor gets a modifier */

#endif /* GUARD_CONSTANTS_DUNGEON_MODIFIERS_H */
