#ifndef GUARD_CONSTANTS_IQ_SKILL_H
#define GUARD_CONSTANTS_IQ_SKILL_H

enum IQSkillID
{
    IQ_NONE,
    IQ_TYPE_ADVANTAGE_MASTER,
    IQ_ITEM_CATCHER,
    IQ_COURSE_CHECKER,
    IQ_SURE_HIT_ATTACKER,
    IQ_QUICK_DODGER,
    IQ_PP_CHECKER,
    IQ_NONTRAITOR,
    IQ_STATUS_CHECKER,
    IQ_EXP_GO_GETTER,
    IQ_EFFICIENCY_EXPERT,
    IQ_WEAK_TYPE_PICKER,
    IQ_ALL_TERRAIN_HIKER,
    IQ_SUPER_MOBILE,
    IQ_TRAP_AVOIDER,
    IQ_HOUSE_AVOIDER,
    IQ_ENERGY_SAVER,
    IQ_NONSLEEPER,
    IQ_SELF_CURER,
    IQ_TRAP_SEER,
    IQ_LAVA_EVADER,
    IQ_DEDICATED_TRAVELER,
    IQ_ITEM_MASTER,
    IQ_EXCLUSIVE_MOVE_USER,
    /* Custom skills (gated by gRuntimeConfig.custom_iq_skills) */
    IQ_CONSERVER,
    IQ_PP_SAVER,
    IQ_TYPE_EXPERT,
    IQ_TYPE_GUARD,
    IQ_STATUS_EXPERT,
    IQ_EFFICIENT_EATER,
    IQ_TREASURE_SENSE,
    NUM_IQ_SKILLS
};

#define IQ_FIRST_CUSTOM_SKILL IQ_CONSERVER

#endif // GUARD_CONSTANTS_IQ_SKILL_H
