namespace RescueEditor.Core;

public static partial class DungeonBuiltinNames
{
    private static readonly string?[] ItemNames =
    [
        "Nothing",
        "Stick",
        "Iron Thorn",
        "Silver Spike",
        "Gold Fang",
        "Cacnea Spike",
        "Corsola Twig",
        "Gravelerock",
        "Geo Pebble",
        "Mobile Scarf",
        "Heal Ribbon",
        "Twist Band",
        "Scope Lens",
        "Patsy Band",
        "Nostick Cap",
        "Pierce Band",
        "Joy Ribbon",
        "X Ray Specs",
        "Persim Band",
        "Power Band",
        "Pecha Scarf",
        "Insomniscope",
        "Warp Scarf",
        "Tight Belt",
        "Sneak Scarf",
        "Gold Ribbon",
        "Goggle Specs",
        "Diet Ribbon",
        "Trap Scarf",
        "Racket Band",
        "Def Scarf",
        "Stamina Band",
        "Plain Ribbon",
        "Special Band",
        "Zinc Band",
        "Detect Band",
        "Alert Specs",
        "Dodge Scarf",
        "Bounce Band",
        "Curve Band",
        "Whiff Specs",
        "No Aim Scope",
        "Lockon Specs",
        "Munch Belt",
        "Pass Scarf",
        "Weather Band",
        "Friend Bow",
        "Beauty Scarf",
        "Sun Ribbon",
        "Lunar Ribbon",
        "Ring D",
        "Ring E",
        "Ring F",
        "Heal Seed",
        "Wish Stone",
        "Oran Berry",
        "Sitrus Berry",
        "Eyedrop Seed",
        "Reviver Seed",
        "Blinker Seed",
        "Doom Seed",
        "Allure Seed",
        "Life Seed",
        "Rawst Berry",
        "Hunger Seed",
        "Quick Seed",
        "Pecha Berry",
        "Cheri Berry",
        "Totter Seed",
        "Sleep Seed",
        "Plain Seed",
        "Warp Seed",
        "Blast Seed",
        "Ginseng",
        "Joy Seed",
        "Chesto Berry",
        "Stun Seed",
        "Max Elixir",
        "Protein",
        "Calcium",
        "Iron",
        "Zinc",
        "Apple",
        "Big Apple",
        "Grimy Food",
        "Huge Apple",
        "White Gummi",
        "Red Gummi",
        "Blue Gummi",
        "Grass Gummi",
        "Yellow Gummi",
        "Clear Gummi",
        "Orange Gummi",
        "Pink Gummi",
        "Brown Gummi",
        "Sky Gummi",
        "Gold Gummi",
        "Green Gummi",
        "Gray Gummi",
        "Purple Gummi",
        "Royal Gummi",
        "Black Gummi",
        "Silver Gummi",
        "Banana",
        "Chestnut",
        "Poke",
        "Upgrade",
        "Kings Rock",
        "Thunderstone",
        "Deepseascale",
        "Deepseatooth",
        "Sun Stone",
        "Moon Stone",
        "Fire Stone",
        "Water Stone",
        "Metal Coat",
        "Leaf Stone",
        "Dragon Scale",
        "Link Cable",
        "Ice Part",
        "Steel Part",
        "Rock Part",
        "Music Box",
        "Key",
        "Tm Used Tm",
        "Tm Focus Punch",
        "Tm Dragon Claw",
        "Tm Water Pulse",
        "Tm Calm Mind",
        "Tm Roar",
        "Tm Toxic",
        "Hail Orb",
        "Tm Bulk Up",
        "Tm Bullet Seed",
        "Tm Hidden Power",
        "Sunny Orb",
        "Tm Taunt",
        "Tm Ice Beam",
        "Tm Blizzard",
        "Tm Hyper Beam",
        "Tm Light Screen",
        "Tm Protect",
        "Rainy Orb",
        "Tm Giga Drain",
        "Tm Safeguard",
        "Tm Frustration",
        "Tm Solarbeam",
        "Tm Iron Tail",
        "Tm Thunderbolt",
        "Tm Thunder",
        "Tm Earthquake",
        "Tm Return",
        "Tm Dig",
        "Tm Psychic",
        "Tm Shadow Ball",
        "Tm Brick Break",
        "Evasion Orb",
        "Tm Reflect",
        "Tm Shock Wave",
        "Tm Flamethrower",
        "Tm Sludge Bomb",
        "Sandy Orb",
        "Tm Fire Blast",
        "Rocky Orb",
        "Tm Aerial Ace",
        "Tm Torment",
        "Tm Facade",
        "Tm Secret Power",
        "Tm Rest",
        "Tm Attract",
        "Tm Thief",
        "Tm Steel Wing",
        "Tm Skill Swap",
        "Snatch Orb",
        "Tm Overheat",
        "Tm Wide Slash",
        "Tm Excavate",
        "Tm Spin Slash",
        "See Trap Orb",
        "Mug Orb",
        "Rebound Orb",
        "Lob Orb",
        "Switcher Orb",
        "Blowback Orb",
        "Warp Orb",
        "Transfer Orb",
        "Slow Orb",
        "Quick Orb",
        "Luminous Orb",
        "Petrify Orb",
        "Stayaway Orb",
        "Pounce Orb",
        "Trawl Orb",
        "Cleanse Orb",
        "Observer Orb",
        "Decoy Orb",
        "Slumber Orb",
        "Totter Orb",
        "Two Edge Orb",
        "Silence Orb",
        "Escape Orb",
        "Scanner Orb",
        "Radar Orb",
        "Drought Orb",
        "Trapbust Orb",
        "Rollcall Orb",
        "Invisify Orb",
        "One Shot Orb",
        "Identify Orb",
        "Tm Vacuum Cut",
        "Reviver Orb",
        "Shocker Orb",
        "Sizebust Orb",
        "One Room Orb",
        "Fill In Orb",
        "Trapper Orb",
        "Possess Orb",
        "Itemizer Orb",
        "Hurl Orb",
        "Mobile Orb",
        "Toss Orb",
        "Stairs Orb",
        "Longtoss Orb",
        "Pierce Orb",
        "Hm Cut",
        "Hm Fly",
        "Hm Surf",
        "Hm Strength",
        "Hm Flash",
        "Hm Rock Smash",
        "Hm Waterfall",
        "Hm Dive",
        "Link Box",
        "Switch Box",
        "Weavile Fig",
        "Mime Jr Fig",
        "Beatup Orb",
        "G Machine 6",
        "G Machine 7",
        "G Machine 8",
    ];

    public static string Item(int id) =>
        (uint)id < (uint)ItemNames.Length && ItemNames[id] is { } name ? name : $"Item {id}";

    public static int ItemCount => ItemNames.Length;

    public static readonly byte[] ItemSpriteIds = [2, 0, 0, 0, 0, 0, 0, 1, 1, 4, 4, 4, 13, 4, 4, 4, 4, 13, 4, 4, 4, 13, 4, 4, 4, 4, 13, 4, 4, 4, 4, 4, 4, 4, 4, 4, 13, 4, 4, 4, 13, 13, 13, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 14, 7, 2, 2, 14, 14, 14, 14, 14, 14, 2, 14, 14, 2, 2, 14, 14, 14, 14, 14, 12, 14, 2, 14, 12, 12, 12, 12, 12, 3, 3, 1, 3, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 19, 11, 6, 5, 5, 1, 20, 5, 1, 1, 1, 1, 5, 1, 20, 5, 18, 18, 18, 5, 16, 8, 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 15, 8, 15, 8, 8, 8, 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 8, 8, 8, 8, 8, 8, 8, 10, 10, 10, 10, 15, 10, 10, 10];
    public static readonly byte[] ItemPaletteIds = [0, 1, 2, 11, 3, 10, 4, 11, 11, 4, 4, 4, 4, 4, 4, 4, 4, 9, 4, 4, 4, 9, 4, 4, 4, 4, 9, 4, 4, 4, 4, 4, 4, 4, 4, 4, 9, 4, 4, 4, 9, 9, 9, 4, 4, 4, 4, 10, 3, 0, 4, 4, 4, 4, 6, 0, 3, 4, 4, 4, 4, 4, 4, 10, 4, 4, 4, 6, 4, 4, 4, 4, 4, 8, 4, 2, 4, 8, 8, 8, 8, 8, 3, 3, 9, 3, 11, 6, 0, 10, 3, 11, 9, 4, 8, 0, 3, 10, 11, 7, 2, 2, 11, 0, 6, 3, 2, 1, 3, 2, 5, 3, 7, 6, 0, 7, 10, 10, 10, 0, 11, 6, 3, 5, 2, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 0, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0];

    public static int ItemSprite(int id) =>
        (uint)id < (uint)ItemSpriteIds.Length ? ItemSpriteIds[id] : 0;

    public static int ItemPalette(int id) =>
        (uint)id < (uint)ItemPaletteIds.Length ? ItemPaletteIds[id] : 0;
}

