namespace RescueEditor.Core;

/// <summary>Decomp names shipped with Core so the Windows mirror can name dungeons without headers.</summary>
public static partial class DungeonBuiltinNames
{
    public sealed record DungeonInfo(string Symbol, string DisplayName, int FloorCount, bool StairDirectionUp);

    public static readonly DungeonInfo[] Dungeons =
    [
        new("DUNGEON_TINY_WOODS", "Tiny Woods", 4, false),
        new("DUNGEON_THUNDERWAVE_CAVE", "Thunderwave Cave", 6, false),
        new("DUNGEON_MT_STEEL", "Mt. Steel", 10, true),
        new("DUNGEON_SINISTER_WOODS", "Sinister Woods", 14, true),
        new("DUNGEON_SILENT_CHASM", "Silent Chasm", 10, false),
        new("DUNGEON_MT_THUNDER", "Mt. Thunder", 11, true),
        new("DUNGEON_MT_THUNDER_PEAK", "Mt. Thunder Peak", 4, true),
        new("DUNGEON_GREAT_CANYON", "Great Canyon", 13, true),
        new("DUNGEON_LAPIS_CAVE", "Lapis Cave", 15, false),
        new("DUNGEON_MT_BLAZE", "Mt. Blaze", 13, true),
        new("DUNGEON_MT_BLAZE_PEAK", "Mt. Blaze Peak", 4, true),
        new("DUNGEON_FROSTY_FOREST", "Frosty Forest", 10, true),
        new("DUNGEON_FROSTY_GROTTO", "Frosty Grotto", 6, true),
        new("DUNGEON_MT_FREEZE", "Mt. Freeze", 16, true),
        new("DUNGEON_MT_FREEZE_PEAK", "Mt. Freeze Peak", 6, true),
        new("DUNGEON_MAGMA_CAVERN", "Magma Cavern", 24, false),
        new("DUNGEON_MAGMA_CAVERN_PIT", "Magma Cavern Pit", 4, false),
        new("DUNGEON_SKY_TOWER", "Sky Tower", 26, true),
        new("DUNGEON_SKY_TOWER_SUMMIT", "Sky Tower Summit", 10, true),
        new("DUNGEON_STORMY_SEA", "Stormy Sea", 41, false),
        new("DUNGEON_SILVER_TRENCH", "Silver Trench", 100, false),
        new("DUNGEON_METEOR_CAVE", "Meteor Cave", 21, false),
        new("DUNGEON_MT_FREEZE_PEAK_2", "Mt. Freeze Peak", 5, true),
        new("DUNGEON_WESTERN_CAVE", "Western Cave", 100, false),
        new("DUNGEON_BOSS_3", "Boss 3", 21, false),
        new("DUNGEON_BOSS_4", "Boss 4", 12, false),
        new("DUNGEON_WISH_CAVE", "Wish Cave", 100, false),
        new("DUNGEON_BURIED_RELIC", "Buried Relic", 100, false),
        new("DUNGEON_PITFALL_VALLEY", "Pitfall Valley", 26, false),
        new("DUNGEON_NORTHERN_RANGE", "Northern Range", 26, true),
        new("DUNGEON_BOSS_9", "Boss 9", 13, false),
        new("DUNGEON_DESERT_REGION", "Desert Region", 21, true),
        new("DUNGEON_SOUTHERN_CAVERN", "Southern Cavern", 51, false),
        new("DUNGEON_WYVERN_HILL", "Wyvern Hill", 31, true),
        new("DUNGEON_FIERY_FIELD", "Fiery Field", 31, true),
        new("DUNGEON_NORTHWIND_FIELD", "Northwind Field", 31, true),
        new("DUNGEON_SOLAR_CAVE", "Solar Cave", 21, false),
        new("DUNGEON_LIGHTNING_FIELD", "Lightning Field", 31, true),
        new("DUNGEON_DARKNIGHT_RELIC", "Darknight Relic", 16, false),
        new("DUNGEON_WONDROUS_SEA", "Wondrous Sea", 13, false),
        new("DUNGEON_MURKY_CAVE", "Murky Cave", 20, false),
        new("DUNGEON_GRAND_SEA", "Grand Sea", 31, false),
        new("DUNGEON_UPROAR_FOREST", "Uproar Forest", 11, false),
        new("DUNGEON_ODDITY_CAVE", "Oddity Cave", 16, false),
        new("DUNGEON_REMAINS_ISLAND", "Remains Island", 21, false),
        new("DUNGEON_MARVELOUS_SEA", "Marvelous Sea", 21, false),
        new("DUNGEON_FANTASY_STRAIT", "Fantasy Strait", 31, false),
        new("DUNGEON_ROCK_PATH", "Rock Path", 5, false),
        new("DUNGEON_SNOW_PATH", "Snow Path", 5, false),
        new("DUNGEON_AUTOPILOT", "Autopilot", 11, false),
        new("DUNGEON_D50", "D50", 3, false),
        new("DUNGEON_D51", "D51", 51, false),
        new("DUNGEON_NORMAL_MAZE", "Dojo Registration", 70, false),
        new("DUNGEON_HOWLING_FOREST", "Howling Forest", 16, true),
        new("DUNGEON_D54", "D54", 31, false),
        new("DUNGEON_POISON_MAZE", "Fantasy Strait", 20, false),
        new("DUNGEON_WATERFALL_POND", "Waterfall Pond", 20, false),
        new("DUNGEON_UNOWN_RELIC", "Unown Relic", 12, false),
        new("DUNGEON_JOYOUS_TOWER", "Joyous Tower", 100, true),
        new("DUNGEON_FAR_OFF_SEA", "Far-off Sea", 76, false),
        new("DUNGEON_MT_FARAWAY", "Mt. Faraway", 41, true),
        new("DUNGEON_D61", "D61", 100, false),
        new("DUNGEON_PURITY_FOREST", "Purity Forest", 100, true),
    ];

    public static readonly string[] Traps =
    [
        "Trip Trap",
        "Mud Trap",
        "Sticky Trap",
        "Grimy Trap",
        "Summon Trap",
        "Pitfall Trap",
        "Warp Trap",
        "Whirlwind Trap",
        "Spin Trap",
        "Slumber Trap",
        "Slow Trap",
        "Seal Trap",
        "Poison Trap",
        "Selfdestruct Trap",
        "Explosion Trap",
        "Pp-Zero Trap",
        "Chestnut Trap",
        "Wonder Tile",
        "Pokemon Trap",
        "Spike Trap",
    ];

    public static readonly string[] Weather =
    ["Clear", "Sunny", "Sandstorm", "Cloudy", "Rain", "Hail", "Fog", "Snow"];

    public static readonly string[] LayoutSymbols =
    [
        "LAYOUT_LARGE",
        "LAYOUT_SMALL",
        "LAYOUT_ONE_ROOM_MONSTER_HOUSE",
        "LAYOUT_OUTER_RING",
        "LAYOUT_CROSSROADS",
        "LAYOUT_TWO_ROOMS_WITH_MONSTER_HOUSE",
        "LAYOUT_LINE",
        "LAYOUT_CROSS",
        "LAYOUT_LARGE_0x8",
        "LAYOUT_BEETLE",
        "LAYOUT_OUTER_ROOMS",
        "LAYOUT_MEDIUM",
        "LAYOUT_UNUSED_0xC",
        "LAYOUT_UNUSED_0xD",
        "LAYOUT_UNUSED_0xE",
        "LAYOUT_UNUSED_0xF",
    ];

    public static readonly string[] Layouts =
    [
        "Large",
        "Small",
        "One Room Monster House",
        "Outer Ring",
        "Crossroads",
        "Two Rooms With Monster House",
        "Line",
        "Cross",
        "Large 8",
        "Beetle",
        "Outer Rooms",
        "Medium",
        "Unused C",
        "Unused D",
        "Unused E",
        "Unused F",
    ];

    public static readonly string[] Darkness =
    [
        "Full",
        "Dark",
        "Dim",
        "Heavy",
    ];

    private static readonly string?[] SpeciesNames =
    [
        "None",
        "Bulbasaur",
        "Ivysaur",
        "Venusaur",
        "Charmander",
        "Charmeleon",
        "Charizard",
        "Squirtle",
        "Wartortle",
        "Blastoise",
        "Caterpie",
        "Metapod",
        "Butterfree",
        "Weedle",
        "Kakuna",
        "Beedrill",
        "Pidgey",
        "Pidgeotto",
        "Pidgeot",
        "Rattata",
        "Raticate",
        "Spearow",
        "Fearow",
        "Ekans",
        "Arbok",
        "Pikachu",
        "Raichu",
        "Sandshrew",
        "Sandslash",
        "Nidoran♀",
        "Nidorina",
        "Nidoqueen",
        "Nidoran♂",
        "Nidorino",
        "Nidoking",
        "Clefairy",
        "Clefable",
        "Vulpix",
        "Ninetales",
        "Jigglypuff",
        "Wigglytuff",
        "Zubat",
        "Golbat",
        "Oddish",
        "Gloom",
        "Vileplume",
        "Paras",
        "Parasect",
        "Venonat",
        "Venomoth",
        "Diglett",
        "Dugtrio",
        "Meowth",
        "Persian",
        "Psyduck",
        "Golduck",
        "Mankey",
        "Primeape",
        "Growlithe",
        "Arcanine",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Abra",
        "Kadabra",
        "Alakazam",
        "Machop",
        "Machoke",
        "Machamp",
        "Bellsprout",
        "Weepinbell",
        "Victreebel",
        "Tentacool",
        "Tentacruel",
        "Geodude",
        "Graveler",
        "Golem",
        "Ponyta",
        "Rapidash",
        "Slowpoke",
        "Slowbro",
        "Magnemite",
        "Magneton",
        "Farfetchd",
        "Doduo",
        "Dodrio",
        "Seel",
        "Dewgong",
        "Grimer",
        "Muk",
        "Shellder",
        "Cloyster",
        "Gastly",
        "Haunter",
        "Gengar",
        "Onix",
        "Drowzee",
        "Hypno",
        "Krabby",
        "Kingler",
        "Voltorb",
        "Electrode",
        "Exeggcute",
        "Exeggutor",
        "Cubone",
        "Marowak",
        "Hitmonlee",
        "Hitmonchan",
        "Lickitung",
        "Koffing",
        "Weezing",
        "Rhyhorn",
        "Rhydon",
        "Chansey",
        "Tangela",
        "Kangaskhan",
        "Horsea",
        "Seadra",
        "Goldeen",
        "Seaking",
        "Staryu",
        "Starmie",
        "Mr. Mime",
        "Scyther",
        "Jynx",
        "Electabuzz",
        "Magmar",
        "Pinsir",
        "Tauros",
        "Magikarp",
        "Gyarados",
        "Lapras",
        "Ditto",
        "Eevee",
        "Vaporeon",
        "Jolteon",
        "Flareon",
        "Porygon",
        "Omanyte",
        "Omastar",
        "Kabuto",
        "Kabutops",
        "Aerodactyl",
        "Snorlax",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Dratini",
        "Dragonair",
        "Dragonite",
        "Mewtwo",
        "Mew",
        "Chikorita",
        "Bayleef",
        "Meganium",
        "Cyndaquil",
        "Quilava",
        "Typhlosion",
        "Totodile",
        "Croconaw",
        "Feraligatr",
        "Sentret",
        "Furret",
        "Hoothoot",
        "Noctowl",
        "Ledyba",
        "Ledian",
        "Spinarak",
        "Ariados",
        "Crobat",
        "Chinchou",
        "Lanturn",
        "Pichu",
        "Cleffa",
        "Igglybuff",
        "Togepi",
        "Togetic",
        "Natu",
        "Xatu",
        "Mareep",
        "Flaaffy",
        "Ampharos",
        "Bellossom",
        "Marill",
        "Azumarill",
        "Sudowoodo",
        "Politoed",
        "Hoppip",
        "Skiploom",
        "Jumpluff",
        "Aipom",
        "Sunkern",
        "Sunflora",
        "Yanma",
        "Wooper",
        "Quagsire",
        "Espeon",
        "Umbreon",
        "Murkrow",
        "Slowking",
        "Misdreavus",
        "Unown A",
        "Unown B",
        "Unown C",
        "Unown D",
        "Unown E",
        "Unown F",
        "Unown G",
        "Unown H",
        "Unown I",
        "Unown J",
        "Unown K",
        "Unown L",
        "Unown M",
        "Unown N",
        "Unown O",
        "Unown P",
        "Unown Q",
        "Unown R",
        "Unown S",
        "Unown T",
        "Unown U",
        "Unown V",
        "Unown W",
        "Unown X",
        "Unown Y",
        "Unown Z",
        "Wobbuffet",
        "Girafarig",
        "Pineco",
        "Forretress",
        "Dunsparce",
        "Gligar",
        "Steelix",
        "Snubbull",
        "Granbull",
        "Qwilfish",
        "Scizor",
        "Shuckle",
        "Heracross",
        "Sneasel",
        "Teddiursa",
        "Ursaring",
        "Slugma",
        "Magcargo",
        "Swinub",
        "Piloswine",
        "Corsola",
        "Remoraid",
        "Octillery",
        "Delibird",
        "Mantine",
        "Skarmory",
        "Houndour",
        "Houndoom",
        "Kingdra",
        "Phanpy",
        "Donphan",
        "Porygon2",
        "Stantler",
        "Smeargle",
        "Tyrogue",
        "Hitmontop",
        "Smoochum",
        "Elekid",
        "Magby",
        "Miltank",
        "Blissey",
        "Raikou",
        "Entei",
        "Suicune",
        "Larvitar",
        "Pupitar",
        "Tyranitar",
        "Lugia",
        "Ho-Oh",
        "Celebi",
        "Treecko",
        "Grovyle",
        "Sceptile",
        "Torchic",
        "Combusken",
        "Blaziken",
        "Mudkip",
        "Marshtomp",
        "Swampert",
        "Poochyena",
        "Mightyena",
        "Zigzagoon",
        "Linoone",
        "Wurmple",
        "Silcoon",
        "Beautifly",
        "Cascoon",
        "Dustox",
        "Lotad",
        "Lombre",
        "Ludicolo",
        "Seedot",
        "Nuzleaf",
        "Shiftry",
        "Taillow",
        "Swellow",
        "Wingull",
        "Pelipper",
        "Ralts",
        "Kirlia",
        "Gardevoir",
        "Surskit",
        "Masquerain",
        "Shroomish",
        "Breloom",
        "Slakoth",
        "Vigoroth",
        "Slaking",
        "Nincada",
        "Ninjask",
        "Shedinja",
        "Whismur",
        "Loudred",
        "Exploud",
        "Makuhita",
        "Hariyama",
        "Azurill",
        "Nosepass",
        "Skitty",
        "Delcatty",
        "Sableye",
        "Mawile",
        "Aron",
        "Lairon",
        "Aggron",
        "Meditite",
        "Medicham",
        "Electrike",
        "Manectric",
        "Plusle",
        "Minun",
        "Volbeat",
        "Illumise",
        "Roselia",
        "Gulpin",
        "Swalot",
        "Carvanha",
        "Sharpedo",
        "Wailmer",
        "Wailord",
        "Numel",
        "Camerupt",
        "Torkoal",
        "Spoink",
        "Grumpig",
        "Spinda",
        "Trapinch",
        "Vibrava",
        "Flygon",
        "Cacnea",
        "Cacturne",
        "Swablu",
        "Altaria",
        "Zangoose",
        "Seviper",
        "Lunatone",
        "Solrock",
        "Barboach",
        "Whiscash",
        "Corphish",
        "Crawdaunt",
        "Baltoy",
        "Claydol",
        "Lileep",
        "Cradily",
        "Anorith",
        "Armaldo",
        "Feebas",
        "Milotic",
        "Castform",
        "Castform Snowy",
        "Castform Sunny",
        "Castform Rainy",
        "Kecleon",
        "Shuppet",
        "Banette",
        "Duskull",
        "Dusclops",
        "Tropius",
        "Chimecho",
        "Absol",
        "Wynaut",
        "Snorunt",
        "Glalie",
        "Spheal",
        "Sealeo",
        "Walrein",
        "Clamperl",
        "Huntail",
        "Gorebyss",
        "Relicanth",
        "Luvdisc",
        "Bagon",
        "Shelgon",
        "Salamence",
        "Beldum",
        "Metang",
        "Metagross",
        "Regirock",
        "Regice",
        "Registeel",
        "Latias",
        "Latios",
        "Kyogre",
        "Groudon",
        "Rayquaza",
        "Jirachi",
        "Deoxys Normal",
        "Unown Emark",
        "Unown Qmark",
        "Deoxys Attack",
        "Deoxys Defense",
        "Deoxys Speed",
        "Munchlax",
        "Decoy",
        "Statue",
        "Rayquaza Cutscene",
    ];

    public static bool TryGetDungeon(int id, out DungeonInfo info)
    {
        if ((uint)id < (uint)Dungeons.Length)
        {
            info = Dungeons[id];
            return true;
        }
        info = null!;
        return false;
    }

    public static string Species(int id) =>
        (uint)id < (uint)SpeciesNames.Length && SpeciesNames[id] is { } name ? name : $"#{id}";

    public static int SpeciesCount => SpeciesNames.Length;
    public const int NationalDexCount = 386;

    public static string Trap(int id) =>
        (uint)id < (uint)Traps.Length ? Traps[id] : $"Trap {id}";

    public static string WeatherName(int id) =>
        (uint)id < (uint)Weather.Length ? Weather[id] : $"Weather {id}";

    public static string LayoutSymbol(int id) =>
        (uint)id < (uint)LayoutSymbols.Length ? LayoutSymbols[id] : $"LAYOUT_{id}";

    public static string LayoutName(int id) =>
        (uint)id < (uint)Layouts.Length ? Layouts[id] : $"Layout {id}";

    public static string DarknessName(int id) =>
        (uint)id < (uint)Darkness.Length ? Darkness[id] : $"Darkness {id}";
}
