.global gKaoAbsol
gKaoAbsol:
kao_siro sPortraitsAbsol
sAbsolNormalPal:
.incbin "graphics/kao/absol_16B9668_40.bin"
sAbsolNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/absol_16B96AD_29B.bin"
sAbsolHappyPal:
.incbin "graphics/kao/absol_16B9948_40.bin"
sAbsolHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/absol_16B998D_287.bin"
sPortraitsAbsol:
kao_portrait sAbsolNormalPal, sAbsolNormalGfx
kao_portrait sAbsolHappyPal, sAbsolHappyGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
