.global gKaoAlakazam
gKaoAlakazam:
kao_siro sPortraitsAlakazam
sAlakazamNormalPal:
.incbin "graphics/kao/alakazam_1692DD0_40.bin"
sAlakazamNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/alakazam_1692E15_2DB.bin"
sAlakazamSurprisedPal:
.incbin "graphics/kao/alakazam_16930F0_40.bin"
sAlakazamSurprisedGfx:
.string "AT4PX"
.incbin "graphics/kao/alakazam_1693135_2F7.bin"
sAlakazamHappyPal:
.incbin "graphics/kao/alakazam_169342C_40.bin"
sAlakazamHappyGfx:
.incbin "graphics/kao/alakazam_169346C_2D8.bin"
sPortraitsAlakazam:
kao_portrait sAlakazamNormalPal, sAlakazamNormalGfx
kao_portrait sAlakazamSurprisedPal, sAlakazamSurprisedGfx
kao_portrait sAlakazamHappyPal, sAlakazamHappyGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
