.global gKaoArticuno
gKaoArticuno:
kao_siro sPortraitsArticuno
sArticunoNormalPal:
.incbin "graphics/kao/articuno_169D748_40.bin"
sArticunoNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/articuno_169D78D_2BB.bin"
sPortraitsArticuno:
kao_portrait sArticunoNormalPal, sArticunoNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
