.global gKaoBellsprout
gKaoBellsprout:
kao_siro sPortraitsBellsprout
sBellsproutNormalPal:
.incbin "graphics/kao/bellsprout_1695DC4_40.bin"
sBellsproutNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/bellsprout_1695E09_26B.bin"
sBellsproutWorriedPal:
.incbin "graphics/kao/bellsprout_1696074_40.bin"
sBellsproutWorriedGfx:
.string "AT4PX"
.incbin "graphics/kao/bellsprout_16960B9_243.bin"
sPortraitsBellsprout:
kao_portrait sBellsproutNormalPal, sBellsproutNormalGfx
kao_portrait sBellsproutWorriedPal, sBellsproutWorriedGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
