.global gKaoBlastoise
gKaoBlastoise:
kao_siro sPortraitsBlastoise
sBlastoiseNormalPal:
.incbin "graphics/kao/blastoise_1687E88_40.bin"
sBlastoiseNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/blastoise_1687ECD_2AB.bin"
sBlastoiseSurprisedPal:
.incbin "graphics/kao/blastoise_1688178_40.bin"
sBlastoiseSurprisedGfx:
.string "AT4PX"
.incbin "graphics/kao/blastoise_16881BD_2A3.bin"
sBlastoiseAngryPal:
.incbin "graphics/kao/blastoise_1688460_40.bin"
sBlastoiseAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/blastoise_16884A5_2B3.bin"
sBlastoisePainedPal:
.incbin "graphics/kao/blastoise_1688758_40.bin"
sBlastoisePainedGfx:
.string "AT4PX"
.incbin "graphics/kao/blastoise_168879D_2A3.bin"
sPortraitsBlastoise:
kao_portrait sBlastoiseNormalPal, sBlastoiseNormalGfx
kao_portrait sBlastoiseSurprisedPal, sBlastoiseSurprisedGfx
kao_portrait sBlastoiseAngryPal, sBlastoiseAngryGfx
kao_portrait sBlastoisePainedPal, sBlastoisePainedGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
