.global gKaoBulbasaur
gKaoBulbasaur:
kao_siro sPortraitsBulbasaur
sBulbasaurNormalPal:
.incbin "graphics/kao/bulbasaur_167FE88_40.bin"
sBulbasaurNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/bulbasaur_167FECD_2BF.bin"
sBulbasaurHappyPal:
.incbin "graphics/kao/bulbasaur_168018C_40.bin"
sBulbasaurHappyGfx:
.incbin "graphics/kao/bulbasaur_16801CC_2AC.bin"
sBulbasaurPainedPal:
.incbin "graphics/kao/bulbasaur_1680478_40.bin"
sBulbasaurPainedGfx:
.string "AT4PX"
.incbin "graphics/kao/bulbasaur_16804BD_2C3.bin"
sBulbasaurAngryPal:
.incbin "graphics/kao/bulbasaur_1680780_40.bin"
sBulbasaurAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/bulbasaur_16807C5_2DF.bin"
sBulbasaurWorriedPal:
.incbin "graphics/kao/bulbasaur_1680AA4_40.bin"
sBulbasaurWorriedGfx:
.incbin "graphics/kao/bulbasaur_1680AE4_2CC.bin"
sBulbasaurSadPal:
.incbin "graphics/kao/bulbasaur_1680DB0_40.bin"
sBulbasaurSadGfx:
.string "AT4PX"
.incbin "graphics/kao/bulbasaur_1680DF5_2A7.bin"
sBulbasaurCryingPal:
.incbin "graphics/kao/bulbasaur_168109C_40.bin"
sBulbasaurCryingGfx:
.incbin "graphics/kao/bulbasaur_16810DC_2BC.bin"
sBulbasaurShoutingPal:
.incbin "graphics/kao/bulbasaur_1681398_40.bin"
sBulbasaurShoutingGfx:
.incbin "graphics/kao/bulbasaur_16813D8_2C8.bin"
sBulbasaurTearyEyePal:
.incbin "graphics/kao/bulbasaur_16816A0_40.bin"
sBulbasaurTearyEyeGfx:
.string "AT4PX"
.incbin "graphics/kao/bulbasaur_16816E5_2A7.bin"
sBulbasaurDeterminedPal:
.incbin "graphics/kao/bulbasaur_168198C_40.bin"
sBulbasaurDeterminedGfx:
.incbin "graphics/kao/bulbasaur_16819CC_2B0.bin"
sBulbasaurJoyousPal:
.incbin "graphics/kao/bulbasaur_1681C7C_40.bin"
sBulbasaurJoyousGfx:
.incbin "graphics/kao/bulbasaur_1681CBC_2C0.bin"
sBulbasaurInspiredPal:
.incbin "graphics/kao/bulbasaur_1681F7C_40.bin"
sBulbasaurInspiredGfx:
.incbin "graphics/kao/bulbasaur_1681FBC_2BC.bin"
sBulbasaurSurprisedPal:
.incbin "graphics/kao/bulbasaur_1682278_40.bin"
sBulbasaurSurprisedGfx:
.incbin "graphics/kao/bulbasaur_16822B8_2D0.bin"
sPortraitsBulbasaur:
kao_portrait sBulbasaurNormalPal, sBulbasaurNormalGfx
kao_portrait sBulbasaurHappyPal, sBulbasaurHappyGfx
kao_portrait sBulbasaurPainedPal, sBulbasaurPainedGfx
kao_portrait sBulbasaurAngryPal, sBulbasaurAngryGfx
kao_portrait sBulbasaurWorriedPal, sBulbasaurWorriedGfx
kao_portrait sBulbasaurSadPal, sBulbasaurSadGfx
kao_portrait sBulbasaurCryingPal, sBulbasaurCryingGfx
kao_portrait sBulbasaurShoutingPal, sBulbasaurShoutingGfx
kao_portrait sBulbasaurTearyEyePal, sBulbasaurTearyEyeGfx
kao_portrait sBulbasaurDeterminedPal, sBulbasaurDeterminedGfx
kao_portrait sBulbasaurJoyousPal, sBulbasaurJoyousGfx
kao_portrait sBulbasaurInspiredPal, sBulbasaurInspiredGfx
kao_portrait sBulbasaurSurprisedPal, sBulbasaurSurprisedGfx
