.global gKaoButterfree
gKaoButterfree:
kao_siro sPortraitsButterfree
sButterfreeNormalPal:
.incbin "graphics/kao/butterfree_1689734_40.bin"
sButterfreeNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/butterfree_1689779_2E7.bin"
sPortraitsButterfree:
kao_portrait sButterfreeNormalPal, sButterfreeNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
