.global gKaoCaterpie
gKaoCaterpie:
kao_siro sPortraitsCaterpie
sCaterpieNormalPal:
.incbin "graphics/kao/caterpie_1688AB8_40.bin"
sCaterpieNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/caterpie_1688AFD_29B.bin"
sCaterpieInspiredPal:
.incbin "graphics/kao/caterpie_1688D98_40.bin"
sCaterpieInspiredGfx:
.string "AT4PX"
.incbin "graphics/kao/caterpie_1688DDD_2AF.bin"
sCaterpieSadPal:
.incbin "graphics/kao/caterpie_168908C_40.bin"
sCaterpieSadGfx:
.incbin "graphics/kao/caterpie_16890CC_298.bin"
sPortraitsCaterpie:
kao_portrait sCaterpieNormalPal, sCaterpieNormalGfx
kao_portrait sCaterpieInspiredPal, sCaterpieInspiredGfx
kao_portrait sCaterpieSadPal, sCaterpieSadGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
