.global gKaoCharmander
gKaoCharmander:
kao_siro sPortraitsCharmander
sCharmanderNormalPal:
.incbin "graphics/kao/charmander_1682600_40.bin"
sCharmanderNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/charmander_1682645_247.bin"
sCharmanderHappyPal:
.incbin "graphics/kao/charmander_168288C_40.bin"
sCharmanderHappyGfx:
.incbin "graphics/kao/charmander_16828CC_234.bin"
sCharmanderPainedPal:
.incbin "graphics/kao/charmander_1682B00_40.bin"
sCharmanderPainedGfx:
.string "AT4PX"
.incbin "graphics/kao/charmander_1682B45_253.bin"
sCharmanderAngryPal:
.incbin "graphics/kao/charmander_1682D98_40.bin"
sCharmanderAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/charmander_1682DDD_27B.bin"
sCharmanderWorriedPal:
.incbin "graphics/kao/charmander_1683058_40.bin"
sCharmanderWorriedGfx:
.incbin "graphics/kao/charmander_1683098_254.bin"
sCharmanderSadPal:
.incbin "graphics/kao/charmander_16832EC_40.bin"
sCharmanderSadGfx:
.incbin "graphics/kao/charmander_168332C_254.bin"
sCharmanderCryingPal:
.incbin "graphics/kao/charmander_1683580_40.bin"
sCharmanderCryingGfx:
.string "AT4PX"
.incbin "graphics/kao/charmander_16835C5_263.bin"
sCharmanderShoutingPal:
.incbin "graphics/kao/charmander_1683828_40.bin"
sCharmanderShoutingGfx:
.incbin "graphics/kao/charmander_1683868_2A8.bin"
sCharmanderTearyEyePal:
.incbin "graphics/kao/charmander_1683B10_40.bin"
sCharmanderTearyEyeGfx:
.string "AT4PX"
.incbin "graphics/kao/charmander_1683B55_25B.bin"
sCharmanderDeterminedPal:
.incbin "graphics/kao/charmander_1683DB0_40.bin"
sCharmanderDeterminedGfx:
.string "AT4PX"
.incbin "graphics/kao/charmander_1683DF5_247.bin"
sCharmanderJoyousPal:
.incbin "graphics/kao/charmander_168403C_40.bin"
sCharmanderJoyousGfx:
.incbin "graphics/kao/charmander_168407C_2E0.bin"
sCharmanderInspiredPal:
.incbin "graphics/kao/charmander_168435C_40.bin"
sCharmanderInspiredGfx:
.incbin "graphics/kao/charmander_168439C_248.bin"
sCharmanderSurprisedPal:
.incbin "graphics/kao/charmander_16845E4_40.bin"
sCharmanderSurprisedGfx:
.incbin "graphics/kao/charmander_1684624_2A4.bin"
sPortraitsCharmander:
kao_portrait sCharmanderNormalPal, sCharmanderNormalGfx
kao_portrait sCharmanderHappyPal, sCharmanderHappyGfx
kao_portrait sCharmanderPainedPal, sCharmanderPainedGfx
kao_portrait sCharmanderAngryPal, sCharmanderAngryGfx
kao_portrait sCharmanderWorriedPal, sCharmanderWorriedGfx
kao_portrait sCharmanderSadPal, sCharmanderSadGfx
kao_portrait sCharmanderCryingPal, sCharmanderCryingGfx
kao_portrait sCharmanderShoutingPal, sCharmanderShoutingGfx
kao_portrait sCharmanderTearyEyePal, sCharmanderTearyEyeGfx
kao_portrait sCharmanderDeterminedPal, sCharmanderDeterminedGfx
kao_portrait sCharmanderJoyousPal, sCharmanderJoyousGfx
kao_portrait sCharmanderInspiredPal, sCharmanderInspiredGfx
kao_portrait sCharmanderSurprisedPal, sCharmanderSurprisedGfx
