.global gKaoCharizard
gKaoCharizard:
kao_siro sPortraitsCharizard
sCharizardNormalPal:
.incbin "graphics/kao/charizard_1684940_40.bin"
sCharizardNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/charizard_1684985_267.bin"
sCharizardSurprisedPal:
.incbin "graphics/kao/charizard_1684BEC_40.bin"
sCharizardSurprisedGfx:
.incbin "graphics/kao/charizard_1684C2C_2B4.bin"
sCharizardLaughingPal:
.incbin "graphics/kao/charizard_1684EE0_40.bin"
sCharizardLaughingGfx:
.string "AT4PX"
.incbin "graphics/kao/charizard_1684F25_28F.bin"
sCharizardPainedPal:
.incbin "graphics/kao/charizard_16851B4_40.bin"
sCharizardPainedGfx:
.string "AT4PX"
.incbin "graphics/kao/charizard_16851F9_2BF.bin"
sCharizardSadPal:
.incbin "graphics/kao/charizard_16854B8_40.bin"
sCharizardSadGfx:
.incbin "graphics/kao/charizard_16854F8_288.bin"
sPortraitsCharizard:
kao_portrait sCharizardNormalPal, sCharizardNormalGfx
kao_portrait sCharizardSurprisedPal, sCharizardSurprisedGfx
kao_portrait sCharizardLaughingPal, sCharizardLaughingGfx
kao_portrait sCharizardPainedPal, sCharizardPainedGfx
kao_portrait sCharizardSadPal, sCharizardSadGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
