.global gKaoChikorita
gKaoChikorita:
kao_siro sPortraitsChikorita
sChikoritaNormalPal:
.incbin "graphics/kao/chikorita_169E534_40.bin"
sChikoritaNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/chikorita_169E579_29F.bin"
sChikoritaHappyPal:
.incbin "graphics/kao/chikorita_169E818_40.bin"
sChikoritaHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/chikorita_169E85D_27F.bin"
sChikoritaPainedPal:
.incbin "graphics/kao/chikorita_169EADC_40.bin"
sChikoritaPainedGfx:
.incbin "graphics/kao/chikorita_169EB1C_290.bin"
sChikoritaAngryPal:
.incbin "graphics/kao/chikorita_169EDAC_40.bin"
sChikoritaAngryGfx:
.incbin "graphics/kao/chikorita_169EDEC_27C.bin"
sChikoritaWorriedPal:
.incbin "graphics/kao/chikorita_169F068_40.bin"
sChikoritaWorriedGfx:
.incbin "graphics/kao/chikorita_169F0A8_294.bin"
sChikoritaSadPal:
.incbin "graphics/kao/chikorita_169F33C_40.bin"
sChikoritaSadGfx:
.incbin "graphics/kao/chikorita_169F37C_2A0.bin"
sChikoritaCryingPal:
.incbin "graphics/kao/chikorita_169F61C_40.bin"
sChikoritaCryingGfx:
.incbin "graphics/kao/chikorita_169F65C_2A8.bin"
sChikoritaShoutingPal:
.incbin "graphics/kao/chikorita_169F904_40.bin"
sChikoritaShoutingGfx:
.incbin "graphics/kao/chikorita_169F944_290.bin"
sChikoritaTearyEyePal:
.incbin "graphics/kao/chikorita_169FBD4_40.bin"
sChikoritaTearyEyeGfx:
.incbin "graphics/kao/chikorita_169FC14_2A4.bin"
sChikoritaDeterminedPal:
.incbin "graphics/kao/chikorita_169FEB8_40.bin"
sChikoritaDeterminedGfx:
.incbin "graphics/kao/chikorita_169FEF8_270.bin"
sChikoritaJoyousPal:
.incbin "graphics/kao/chikorita_16A0168_40.bin"
sChikoritaJoyousGfx:
.incbin "graphics/kao/chikorita_16A01A8_2C0.bin"
sChikoritaInspiredPal:
.incbin "graphics/kao/chikorita_16A0468_40.bin"
sChikoritaInspiredGfx:
.incbin "graphics/kao/chikorita_16A04A8_29C.bin"
sChikoritaSurprisedPal:
.incbin "graphics/kao/chikorita_16A0744_40.bin"
sChikoritaSurprisedGfx:
.incbin "graphics/kao/chikorita_16A0784_2AC.bin"
sPortraitsChikorita:
kao_portrait sChikoritaNormalPal, sChikoritaNormalGfx
kao_portrait sChikoritaHappyPal, sChikoritaHappyGfx
kao_portrait sChikoritaPainedPal, sChikoritaPainedGfx
kao_portrait sChikoritaAngryPal, sChikoritaAngryGfx
kao_portrait sChikoritaWorriedPal, sChikoritaWorriedGfx
kao_portrait sChikoritaSadPal, sChikoritaSadGfx
kao_portrait sChikoritaCryingPal, sChikoritaCryingGfx
kao_portrait sChikoritaShoutingPal, sChikoritaShoutingGfx
kao_portrait sChikoritaTearyEyePal, sChikoritaTearyEyeGfx
kao_portrait sChikoritaDeterminedPal, sChikoritaDeterminedGfx
kao_portrait sChikoritaJoyousPal, sChikoritaJoyousGfx
kao_portrait sChikoritaInspiredPal, sChikoritaInspiredGfx
kao_portrait sChikoritaSurprisedPal, sChikoritaSurprisedGfx
