.global gKaoCubone
gKaoCubone:
kao_siro sPortraitsCubone
sCuboneNormalPal:
.incbin "graphics/kao/cubone_1698274_40.bin"
sCuboneNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/cubone_16982B9_2DB.bin"
sCuboneHappyPal:
.incbin "graphics/kao/cubone_1698594_40.bin"
sCuboneHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/cubone_16985D9_2CF.bin"
sCubonePainedPal:
.incbin "graphics/kao/cubone_16988A8_40.bin"
sCubonePainedGfx:
.string "AT4PX"
.incbin "graphics/kao/cubone_16988ED_2B7.bin"
sCuboneAngryPal:
.incbin "graphics/kao/cubone_1698BA4_40.bin"
sCuboneAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/cubone_1698BE9_2D7.bin"
sCuboneWorriedPal:
.incbin "graphics/kao/cubone_1698EC0_40.bin"
sCuboneWorriedGfx:
.incbin "graphics/kao/cubone_1698F00_2AC.bin"
sCuboneSadPal:
.incbin "graphics/kao/cubone_16991AC_40.bin"
sCuboneSadGfx:
.incbin "graphics/kao/cubone_16991EC_2C4.bin"
sCuboneCryingPal:
.incbin "graphics/kao/cubone_16994B0_40.bin"
sCuboneCryingGfx:
.string "AT4PX"
.incbin "graphics/kao/cubone_16994F5_2B7.bin"
sCuboneShoutingPal:
.incbin "graphics/kao/cubone_16997AC_40.bin"
sCuboneShoutingGfx:
.incbin "graphics/kao/cubone_16997EC_2F4.bin"
sCuboneTearyEyePal:
.incbin "graphics/kao/cubone_1699AE0_40.bin"
sCuboneTearyEyeGfx:
.string "AT4PX"
.incbin "graphics/kao/cubone_1699B25_2E3.bin"
sCuboneDeterminedPal:
.incbin "graphics/kao/cubone_1699E08_40.bin"
sCuboneDeterminedGfx:
.incbin "graphics/kao/cubone_1699E48_2B0.bin"
sCuboneJoyousPal:
.incbin "graphics/kao/cubone_169A0F8_40.bin"
sCuboneJoyousGfx:
.incbin "graphics/kao/cubone_169A138_2C8.bin"
sCuboneInspiredPal:
.incbin "graphics/kao/cubone_169A400_40.bin"
sCuboneInspiredGfx:
.string "AT4PX"
.incbin "graphics/kao/cubone_169A445_2DB.bin"
sCuboneSurprisedPal:
.incbin "graphics/kao/cubone_169A720_40.bin"
sCuboneSurprisedGfx:
.string "AT4PX"
.incbin "graphics/kao/cubone_169A765_2E3.bin"
sPortraitsCubone:
kao_portrait sCuboneNormalPal, sCuboneNormalGfx
kao_portrait sCuboneHappyPal, sCuboneHappyGfx
kao_portrait sCubonePainedPal, sCubonePainedGfx
kao_portrait sCuboneAngryPal, sCuboneAngryGfx
kao_portrait sCuboneWorriedPal, sCuboneWorriedGfx
kao_portrait sCuboneSadPal, sCuboneSadGfx
kao_portrait sCuboneCryingPal, sCuboneCryingGfx
kao_portrait sCuboneShoutingPal, sCuboneShoutingGfx
kao_portrait sCuboneTearyEyePal, sCuboneTearyEyeGfx
kao_portrait sCuboneDeterminedPal, sCuboneDeterminedGfx
kao_portrait sCuboneJoyousPal, sCuboneJoyousGfx
kao_portrait sCuboneInspiredPal, sCuboneInspiredGfx
kao_portrait sCuboneSurprisedPal, sCuboneSurprisedGfx
