.global gKaoCyndaquil
gKaoCyndaquil:
kao_siro sPortraitsCyndaquil
sCyndaquilNormalPal:
.incbin "graphics/kao/cyndaquil_16A0AA8_40.bin"
sCyndaquilNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/cyndaquil_16A0AED_26B.bin"
sCyndaquilHappyPal:
.incbin "graphics/kao/cyndaquil_16A0D58_40.bin"
sCyndaquilHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/cyndaquil_16A0D9D_257.bin"
sCyndaquilPainedPal:
.incbin "graphics/kao/cyndaquil_16A0FF4_40.bin"
sCyndaquilPainedGfx:
.string "AT4PX"
.incbin "graphics/kao/cyndaquil_16A1039_2A3.bin"
sCyndaquilAngryPal:
.incbin "graphics/kao/cyndaquil_16A12DC_40.bin"
sCyndaquilAngryGfx:
.incbin "graphics/kao/cyndaquil_16A131C_2D8.bin"
sCyndaquilWorriedPal:
.incbin "graphics/kao/cyndaquil_16A15F4_40.bin"
sCyndaquilWorriedGfx:
.incbin "graphics/kao/cyndaquil_16A1634_258.bin"
sCyndaquilSadPal:
.incbin "graphics/kao/cyndaquil_16A188C_40.bin"
sCyndaquilSadGfx:
.incbin "graphics/kao/cyndaquil_16A18CC_288.bin"
sCyndaquilCryingPal:
.incbin "graphics/kao/cyndaquil_16A1B54_40.bin"
sCyndaquilCryingGfx:
.incbin "graphics/kao/cyndaquil_16A1B94_270.bin"
sCyndaquilShoutingPal:
.incbin "graphics/kao/cyndaquil_16A1E04_40.bin"
sCyndaquilShoutingGfx:
.incbin "graphics/kao/cyndaquil_16A1E44_2C4.bin"
sCyndaquilTearyEyePal:
.incbin "graphics/kao/cyndaquil_16A2108_40.bin"
sCyndaquilTearyEyeGfx:
.incbin "graphics/kao/cyndaquil_16A2148_28C.bin"
sCyndaquilDeterminedPal:
.incbin "graphics/kao/cyndaquil_16A23D4_40.bin"
sCyndaquilDeterminedGfx:
.incbin "graphics/kao/cyndaquil_16A2414_270.bin"
sCyndaquilJoyousPal:
.incbin "graphics/kao/cyndaquil_16A2684_40.bin"
sCyndaquilJoyousGfx:
.incbin "graphics/kao/cyndaquil_16A26C4_2A4.bin"
sCyndaquilInspiredPal:
.incbin "graphics/kao/cyndaquil_16A2968_40.bin"
sCyndaquilInspiredGfx:
.incbin "graphics/kao/cyndaquil_16A29A8_29C.bin"
sCyndaquilSurprisedPal:
.incbin "graphics/kao/cyndaquil_16A2C44_40.bin"
sCyndaquilSurprisedGfx:
.incbin "graphics/kao/cyndaquil_16A2C84_270.bin"
sPortraitsCyndaquil:
kao_portrait sCyndaquilNormalPal, sCyndaquilNormalGfx
kao_portrait sCyndaquilHappyPal, sCyndaquilHappyGfx
kao_portrait sCyndaquilPainedPal, sCyndaquilPainedGfx
kao_portrait sCyndaquilAngryPal, sCyndaquilAngryGfx
kao_portrait sCyndaquilWorriedPal, sCyndaquilWorriedGfx
kao_portrait sCyndaquilSadPal, sCyndaquilSadGfx
kao_portrait sCyndaquilCryingPal, sCyndaquilCryingGfx
kao_portrait sCyndaquilShoutingPal, sCyndaquilShoutingGfx
kao_portrait sCyndaquilTearyEyePal, sCyndaquilTearyEyeGfx
kao_portrait sCyndaquilDeterminedPal, sCyndaquilDeterminedGfx
kao_portrait sCyndaquilJoyousPal, sCyndaquilJoyousGfx
kao_portrait sCyndaquilInspiredPal, sCyndaquilInspiredGfx
kao_portrait sCyndaquilSurprisedPal, sCyndaquilSurprisedGfx
