.global gKaoDeoxysNormal
gKaoDeoxysNormal:
kao_siro sPortraitsDeoxysNormal
sDeoxysNormalNormalPal:
.incbin "graphics/kao/deoxysnormal_16BBBC4_40.bin"
sDeoxysNormalNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/deoxysnormal_16BBC09_277.bin"
sPortraitsDeoxysNormal:
kao_portrait sDeoxysNormalNormalPal, sDeoxysNormalNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
