.global gKaoDiglett
gKaoDiglett:
kao_siro sPortraitsDiglett
sDiglettNormalPal:
.incbin "graphics/kao/diglett_168CE18_40.bin"
sDiglettNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/diglett_168CE5D_1FB.bin"
sDiglettSurprisedPal:
.incbin "graphics/kao/diglett_168D058_40.bin"
sDiglettSurprisedGfx:
.string "AT4PX"
.incbin "graphics/kao/diglett_168D09D_1F7.bin"
sPortraitsDiglett:
kao_portrait sDiglettNormalPal, sDiglettNormalGfx
kao_portrait sDiglettSurprisedPal, sDiglettSurprisedGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
