.global gKaoDugtrio
gKaoDugtrio:
kao_siro sPortraitsDugtrio
sDugtrioNormalPal:
.incbin "graphics/kao/dugtrio_168D30C_40.bin"
sDugtrioNormalGfx:
.incbin "graphics/kao/dugtrio_168D34C_270.bin"
sPortraitsDugtrio:
kao_portrait sDugtrioNormalPal, sDugtrioNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
