.global gKaoEevee
gKaoEevee:
kao_siro sPortraitsEevee
sEeveeNormalPal:
.incbin "graphics/kao/eevee_169B114_40.bin"
sEeveeNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/eevee_169B159_2B7.bin"
sEeveeHappyPal:
.incbin "graphics/kao/eevee_169B410_40.bin"
sEeveeHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/eevee_169B455_29F.bin"
sEeveePainedPal:
.incbin "graphics/kao/eevee_169B6F4_40.bin"
sEeveePainedGfx:
.string "AT4PX"
.incbin "graphics/kao/eevee_169B739_267.bin"
sEeveeAngryPal:
.incbin "graphics/kao/eevee_169B9A0_40.bin"
sEeveeAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/eevee_169B9E5_2BB.bin"
sEeveeWorriedPal:
.incbin "graphics/kao/eevee_169BCA0_40.bin"
sEeveeWorriedGfx:
.string "AT4PX"
.incbin "graphics/kao/eevee_169BCE5_28F.bin"
sEeveeSadPal:
.incbin "graphics/kao/eevee_169BF74_40.bin"
sEeveeSadGfx:
.incbin "graphics/kao/eevee_169BFB4_288.bin"
sEeveeCryingPal:
.incbin "graphics/kao/eevee_169C23C_40.bin"
sEeveeCryingGfx:
.incbin "graphics/kao/eevee_169C27C_278.bin"
sEeveeShoutingPal:
.incbin "graphics/kao/eevee_169C4F4_40.bin"
sEeveeShoutingGfx:
.incbin "graphics/kao/eevee_169C534_2A0.bin"
sEeveeTearyEyePal:
.incbin "graphics/kao/eevee_169C7D4_40.bin"
sEeveeTearyEyeGfx:
.incbin "graphics/kao/eevee_169C814_2B4.bin"
sEeveeDeterminedPal:
.incbin "graphics/kao/eevee_169CAC8_40.bin"
sEeveeDeterminedGfx:
.incbin "graphics/kao/eevee_169CB08_2A4.bin"
sEeveeJoyousPal:
.incbin "graphics/kao/eevee_169CDAC_40.bin"
sEeveeJoyousGfx:
.incbin "graphics/kao/eevee_169CDEC_2D4.bin"
sEeveeInspiredPal:
.incbin "graphics/kao/eevee_169D0C0_40.bin"
sEeveeInspiredGfx:
.string "AT4PX"
.incbin "graphics/kao/eevee_169D105_2BF.bin"
sEeveeSurprisedPal:
.incbin "graphics/kao/eevee_169D3C4_40.bin"
sEeveeSurprisedGfx:
.incbin "graphics/kao/eevee_169D404_2C4.bin"
sPortraitsEevee:
kao_portrait sEeveeNormalPal, sEeveeNormalGfx
kao_portrait sEeveeHappyPal, sEeveeHappyGfx
kao_portrait sEeveePainedPal, sEeveePainedGfx
kao_portrait sEeveeAngryPal, sEeveeAngryGfx
kao_portrait sEeveeWorriedPal, sEeveeWorriedGfx
kao_portrait sEeveeSadPal, sEeveeSadGfx
kao_portrait sEeveeCryingPal, sEeveeCryingGfx
kao_portrait sEeveeShoutingPal, sEeveeShoutingGfx
kao_portrait sEeveeTearyEyePal, sEeveeTearyEyeGfx
kao_portrait sEeveeDeterminedPal, sEeveeDeterminedGfx
kao_portrait sEeveeJoyousPal, sEeveeJoyousGfx
kao_portrait sEeveeInspiredPal, sEeveeInspiredGfx
kao_portrait sEeveeSurprisedPal, sEeveeSurprisedGfx
.string "pksdir0\0"
