.global gKaoEkans
gKaoEkans:
kao_siro sPortraitsEkans
sEkansNormalPal:
.incbin "graphics/kao/ekans_1689AD8_40.bin"
sEkansNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/ekans_1689B1D_23B.bin"
sEkansSurprisedPal:
.incbin "graphics/kao/ekans_1689D58_40.bin"
sEkansSurprisedGfx:
.string "AT4PX"
.incbin "graphics/kao/ekans_1689D9D_2A3.bin"
sEkansHappyPal:
.incbin "graphics/kao/ekans_168A040_40.bin"
sEkansHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/ekans_168A085_24F.bin"
sPortraitsEkans:
kao_portrait sEkansNormalPal, sEkansNormalGfx
kao_portrait sEkansSurprisedPal, sEkansSurprisedGfx
kao_portrait sEkansHappyPal, sEkansHappyGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
