.global gKaoEntei
gKaoEntei:
kao_siro sPortraitsEntei
sEnteiNormalPal:
.incbin "graphics/kao/entei_16A81F0_40.bin"
sEnteiNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/entei_16A8235_2B7.bin"
sPortraitsEntei:
kao_portrait sEnteiNormalPal, sEnteiNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
