.global gKaoGardevoir
gKaoGardevoir:
kao_siro sPortraitsGardevoir
sGardevoirNormalPal:
.incbin "graphics/kao/gardevoir_16B2D34_40.bin"
sGardevoirNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/gardevoir_16B2D79_29F.bin"
sGardevoirHappyPal:
.incbin "graphics/kao/gardevoir_16B3018_40.bin"
sGardevoirHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/gardevoir_16B305D_293.bin"
sGardevoirSadPal:
.incbin "graphics/kao/gardevoir_16B32F0_40.bin"
sGardevoirSadGfx:
.string "AT4PX"
.incbin "graphics/kao/gardevoir_16B3335_27F.bin"
sPortraitsGardevoir:
kao_portrait sGardevoirNormalPal, sGardevoirNormalGfx
kao_portrait sGardevoirHappyPal, sGardevoirHappyGfx
kao_portrait sGardevoirSadPal, sGardevoirSadGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
