.global gKaoGengar
gKaoGengar:
kao_siro sPortraitsGengar
sGengarNormalPal:
.incbin "graphics/kao/gengar_1696D48_40.bin"
sGengarNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/gengar_1696D8D_2C3.bin"
sGengarHappyPal:
.incbin "graphics/kao/gengar_1697050_40.bin"
sGengarHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/gengar_1697095_2A3.bin"
sGengarAngryPal:
.incbin "graphics/kao/gengar_1697338_40.bin"
sGengarAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/gengar_169737D_2BF.bin"
sGengarWorriedPal:
.incbin "graphics/kao/gengar_169763C_40.bin"
sGengarWorriedGfx:
.incbin "graphics/kao/gengar_169767C_29C.bin"
sGengarDejectedPal:
.incbin "graphics/kao/gengar_1697918_40.bin"
sGengarDejectedGfx:
.incbin "graphics/kao/gengar_1697958_2A4.bin"
sGengarSadPal:
.incbin "graphics/kao/gengar_1697BFC_40.bin"
sGengarSadGfx:
.incbin "graphics/kao/gengar_1697C3C_2B4.bin"
sGengarSurprisedPal:
.incbin "graphics/kao/gengar_1697EF0_40.bin"
sGengarSurprisedGfx:
.string "AT4PX"
.incbin "graphics/kao/gengar_1697F35_2C7.bin"
sPortraitsGengar:
kao_portrait sGengarNormalPal, sGengarNormalGfx
kao_portrait sGengarHappyPal, sGengarHappyGfx
kao_portrait sGengarAngryPal, sGengarAngryGfx
kao_portrait sGengarWorriedPal, sGengarWorriedGfx
kao_portrait sGengarDejectedPal, sGengarDejectedGfx
kao_portrait sGengarSadPal, sGengarSadGfx
kao_portrait sGengarSurprisedPal, sGengarSurprisedGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
