.global gKaoGolem
gKaoGolem:
kao_siro sPortraitsGolem
sGolemNormalPal:
.incbin "graphics/kao/golem_1696374_40.bin"
sGolemNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/golem_16963B9_2AB.bin"
sPortraitsGolem:
kao_portrait sGolemNormalPal, sGolemNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
