.global gKaoGranbull
gKaoGranbull:
kao_siro sPortraitsGranbull
sGranbullNormalPal:
.incbin "graphics/kao/granbull_16A6F18_40.bin"
sGranbullNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/granbull_16A6F5D_2F7.bin"
sPortraitsGranbull:
kao_portrait sGranbullNormalPal, sGranbullNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
