.global gKaoGroudon
gKaoGroudon:
kao_siro sPortraitsGroudon
sGroudonNormalPal:
.incbin "graphics/kao/groudon_16BAECC_40.bin"
sGroudonNormalGfx:
.incbin "graphics/kao/groudon_16BAF0C_2F0.bin"
sPortraitsGroudon:
kao_portrait sGroudonNormalPal, sGroudonNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
