.global gKaoGulpin
gKaoGulpin:
kao_siro sPortraitsGulpin
sGulpinNormalPal:
.incbin "graphics/kao/gulpin_16B7474_40.bin"
sGulpinNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/gulpin_16B74B9_213.bin"
sPortraitsGulpin:
kao_portrait sGulpinNormalPal, sGulpinNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
