.global gKaoHoOh
gKaoHoOh:
kao_siro sPortraitsHoOh
sHoOhNormalPal:
.incbin "graphics/kao/hooh_16A9284_40.bin"
sHoOhNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/hooh_16A92C9_2D3.bin"
sPortraitsHoOh:
kao_portrait sHoOhNormalPal, sHoOhNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
