.global gKaoJirachi
gKaoJirachi:
kao_siro sPortraitsJirachi
sJirachiNormalPal:
.incbin "graphics/kao/jirachi_16BB5FC_40.bin"
sJirachiNormalGfx:
.incbin "graphics/kao/jirachi_16BB63C_250.bin"
sJirachiHappyPal:
.incbin "graphics/kao/jirachi_16BB88C_40.bin"
sJirachiHappyGfx:
.incbin "graphics/kao/jirachi_16BB8CC_280.bin"
sPortraitsJirachi:
kao_portrait sJirachiNormalPal, sJirachiNormalGfx
kao_portrait sJirachiHappyPal, sJirachiHappyGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
