.global gKaoJumpluff
gKaoJumpluff:
kao_siro sPortraitsJumpluff
sJumpluffNormalPal:
.incbin "graphics/kao/jumpluff_16A5998_40.bin"
sJumpluffNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/jumpluff_16A59DD_283.bin"
sJumpluffHappyPal:
.incbin "graphics/kao/jumpluff_16A5C60_40.bin"
sJumpluffHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/jumpluff_16A5CA5_283.bin"
sPortraitsJumpluff:
kao_portrait sJumpluffNormalPal, sJumpluffNormalGfx
kao_portrait sJumpluffHappyPal, sJumpluffHappyGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
