.global gKaoKangaskhan
gKaoKangaskhan:
kao_siro sPortraitsKangaskhan
sKangaskhanNormalPal:
.incbin "graphics/kao/kangaskhan_169AAC0_40.bin"
sKangaskhanNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/kangaskhan_169AB05_2AF.bin"
sKangaskhanHappyPal:
.incbin "graphics/kao/kangaskhan_169ADB4_40.bin"
sKangaskhanHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/kangaskhan_169ADF9_2A3.bin"
sPortraitsKangaskhan:
kao_portrait sKangaskhanNormalPal, sKangaskhanNormalGfx
kao_portrait sKangaskhanHappyPal, sKangaskhanHappyGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
