.global gKaoKecleon
gKaoKecleon:
kao_siro sPortraitsKecleon
sKecleonNormalPal:
.incbin "graphics/kao/kecleon_16B8960_40.bin"
sKecleonNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/kecleon_16B89A5_2DF.bin"
sKecleon1Pal:
.incbin "graphics/kao/kecleon_16B8C84_40.bin"
sKecleon1Gfx:
.string "AT4PX"
.incbin "graphics/kao/kecleon_16B8CC9_2E3.bin"
gUnknown_96B8FAC:
.incbin "graphics/kao/kecleon_16B8FAC_40.bin"
gUnknown_96B8FEC:
.incbin "graphics/kao/kecleon_16B8FEC_2DC.bin"
gUnknown_96B92C8:
.incbin "graphics/kao/kecleon_16B92C8_40.bin"
gUnknown_96B9308:
.incbin "graphics/kao/kecleon_16B9308_2E8.bin"
sPortraitsKecleon:
kao_portrait sKecleonNormalPal, sKecleonNormalGfx
kao_portrait sKecleon1Pal, sKecleon1Gfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait gUnknown_96B8FAC, gUnknown_96B8FEC
kao_portrait gUnknown_96B92C8, gUnknown_96B9308
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
