.global gKaoKyogre
gKaoKyogre:
kao_siro sPortraitsKyogre
sKyogreNormalPal:
.incbin "graphics/kao/kyogre_16BABB0_40.bin"
sKyogreNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/kyogre_16BABF5_257.bin"
sPortraitsKyogre:
kao_portrait sKyogreNormalPal, sKyogreNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
