.global gKaoLatias
gKaoLatias:
kao_siro sPortraitsLatias
sLatiasNormalPal:
.incbin "graphics/kao/latias_16BA000_40.bin"
sLatiasNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/latias_16BA045_24B.bin"
sLatiasHappyPal:
.incbin "graphics/kao/latias_16BA290_40.bin"
sLatiasHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/latias_16BA2D5_23F.bin"
sPortraitsLatias:
kao_portrait sLatiasNormalPal, sLatiasNormalGfx
kao_portrait sLatiasHappyPal, sLatiasHappyGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
