.global gKaoLatios
gKaoLatios:
kao_siro sPortraitsLatios
sLatiosNormalPal:
.incbin "graphics/kao/latios_16BA58C_40.bin"
sLatiosNormalGfx:
.incbin "graphics/kao/latios_16BA5CC_290.bin"
sLatiosHappyPal:
.incbin "graphics/kao/latios_16BA85C_40.bin"
sLatiosHappyGfx:
.incbin "graphics/kao/latios_16BA89C_29C.bin"
sPortraitsLatios:
kao_portrait sLatiosNormalPal, sLatiosNormalGfx
kao_portrait sLatiosHappyPal, sLatiosHappyGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
