.global gKaoLombre
gKaoLombre:
kao_siro sPortraitsLombre
sLombreNormalPal:
.incbin "graphics/kao/lombre_16B06C4_40.bin"
sLombreNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/lombre_16B0709_297.bin"
sLombreAngryPal:
.incbin "graphics/kao/lombre_16B09A0_40.bin"
sLombreAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/lombre_16B09E5_26B.bin"
sLombreOpenMouthPal:
.incbin "graphics/kao/lombre_16B0C50_40.bin"
sLombreOpenMouthGfx:
.string "AT4PX"
.incbin "graphics/kao/lombre_16B0C95_29F.bin"
sLombreSadPal:
.incbin "graphics/kao/lombre_16B0F34_40.bin"
sLombreSadGfx:
.string "AT4PX"
.incbin "graphics/kao/lombre_16B0F79_26B.bin"
sLombreNormalFlipPal:
.incbin "graphics/kao/lombre_16B11E4_40.bin"
sLombreNormalFlipGfx:
.incbin "graphics/kao/lombre_16B1224_298.bin"
sLombreAngryFlipPal:
.incbin "graphics/kao/lombre_16B14BC_40.bin"
sLombreAngryFlipGfx:
.incbin "graphics/kao/lombre_16B14FC_260.bin"
sLombreOpenMouthFlipPal:
.incbin "graphics/kao/lombre_16B175C_40.bin"
sLombreOpenMouthFlipGfx:
.incbin "graphics/kao/lombre_16B179C_2A4.bin"
sLombreSadFlipPal:
.incbin "graphics/kao/lombre_16B1A40_40.bin"
sLombreSadFlipGfx:
.string "AT4PX"
.incbin "graphics/kao/lombre_16B1A85_267.bin"
sPortraitsLombre:
kao_portrait sLombreNormalPal, sLombreNormalGfx
kao_portrait sLombreAngryPal, sLombreAngryGfx
kao_portrait sLombreOpenMouthPal, sLombreOpenMouthGfx
kao_portrait sLombreSadPal, sLombreSadGfx
kao_portrait sLombreNormalFlipPal, sLombreNormalFlipGfx
kao_portrait sLombreAngryFlipPal, sLombreAngryFlipGfx
kao_portrait sLombreOpenMouthFlipPal, sLombreOpenMouthFlipGfx
kao_portrait sLombreSadFlipPal, sLombreSadFlipGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
