.global gKaoLugia
gKaoLugia:
kao_siro sPortraitsLugia
sLugiaNormalPal:
.incbin "graphics/kao/lugia_16A8F44_40.bin"
sLugiaNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/lugia_16A8F89_27B.bin"
sPortraitsLugia:
kao_portrait sLugiaNormalPal, sLugiaNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
