.global gKaoMachop
gKaoMachop:
kao_siro sPortraitsMachop
sMachopNormalPal:
.incbin "graphics/kao/machop_16937BC_40.bin"
sMachopNormalGfx:
.incbin "graphics/kao/machop_16937FC_284.bin"
sMachopHappyPal:
.incbin "graphics/kao/machop_1693A80_40.bin"
sMachopHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/machop_1693AC5_25B.bin"
sMachopPainedPal:
.incbin "graphics/kao/machop_1693D20_40.bin"
sMachopPainedGfx:
.string "AT4PX"
.incbin "graphics/kao/machop_1693D65_2B3.bin"
sMachopAngryPal:
.incbin "graphics/kao/machop_1694018_40.bin"
sMachopAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/machop_169405D_2B7.bin"
sMachopWorriedPal:
.incbin "graphics/kao/machop_1694314_40.bin"
sMachopWorriedGfx:
.incbin "graphics/kao/machop_1694354_2B4.bin"
sMachopSadPal:
.incbin "graphics/kao/machop_1694608_40.bin"
sMachopSadGfx:
.incbin "graphics/kao/machop_1694648_2A4.bin"
sMachopCryingPal:
.incbin "graphics/kao/machop_16948EC_40.bin"
sMachopCryingGfx:
.incbin "graphics/kao/machop_169492C_2AC.bin"
sMachopShoutingPal:
.incbin "graphics/kao/machop_1694BD8_40.bin"
sMachopShoutingGfx:
.incbin "graphics/kao/machop_1694C18_2B8.bin"
sMachopTearyEyePal:
.incbin "graphics/kao/machop_1694ED0_40.bin"
sMachopTearyEyeGfx:
.string "AT4PX"
.incbin "graphics/kao/machop_1694F15_283.bin"
sMachopDeterminedPal:
.incbin "graphics/kao/machop_1695198_40.bin"
sMachopDeterminedGfx:
.incbin "graphics/kao/machop_16951D8_274.bin"
sMachopJoyousPal:
.incbin "graphics/kao/machop_169544C_40.bin"
sMachopJoyousGfx:
.incbin "graphics/kao/machop_169548C_2D4.bin"
sMachopInspiredPal:
.incbin "graphics/kao/machop_1695760_40.bin"
sMachopInspiredGfx:
.string "AT4PX"
.incbin "graphics/kao/machop_16957A5_28B.bin"
sMachopSurprisedPal:
.incbin "graphics/kao/machop_1695A30_40.bin"
sMachopSurprisedGfx:
.string "AT4PX"
.incbin "graphics/kao/machop_1695A75_2D7.bin"
sPortraitsMachop:
kao_portrait sMachopNormalPal, sMachopNormalGfx
kao_portrait sMachopHappyPal, sMachopHappyGfx
kao_portrait sMachopPainedPal, sMachopPainedGfx
kao_portrait sMachopAngryPal, sMachopAngryGfx
kao_portrait sMachopWorriedPal, sMachopWorriedGfx
kao_portrait sMachopSadPal, sMachopSadGfx
kao_portrait sMachopCryingPal, sMachopCryingGfx
kao_portrait sMachopShoutingPal, sMachopShoutingGfx
kao_portrait sMachopTearyEyePal, sMachopTearyEyeGfx
kao_portrait sMachopDeterminedPal, sMachopDeterminedGfx
kao_portrait sMachopJoyousPal, sMachopJoyousGfx
kao_portrait sMachopInspiredPal, sMachopInspiredGfx
kao_portrait sMachopSurprisedPal, sMachopSurprisedGfx
