.global gKaoMagnemite
gKaoMagnemite:
kao_siro sPortraitsMagnemite
sMagnemiteNormalPal:
.incbin "graphics/kao/magnemite_16966DC_40.bin"
sMagnemiteNormalGfx:
.incbin "graphics/kao/magnemite_169671C_2B8.bin"
sMagnemiteHappyPal:
.incbin "graphics/kao/magnemite_16969D4_40.bin"
sMagnemiteHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/magnemite_1696A19_2B7.bin"
sPortraitsMagnemite:
kao_portrait sMagnemiteNormalPal, sMagnemiteNormalGfx
kao_portrait sMagnemiteHappyPal, sMagnemiteHappyGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
