.global gKaoMakuhita
gKaoMakuhita:
kao_siro sPortraitsMakuhita
sMakuhitaNormalPal:
.incbin "graphics/kao/makuhita_16B362C_40.bin"
sMakuhitaNormalGfx:
.incbin "graphics/kao/makuhita_16B366C_29C.bin"
sPortraitsMakuhita:
kao_portrait sMakuhitaNormalPal, sMakuhitaNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
