.global gKaoMankey
gKaoMankey:
kao_siro sPortraitsMankey
sMankeyNormalPal:
.incbin "graphics/kao/mankey_169271C_40.bin"
sMankeyNormalGfx:
.incbin "graphics/kao/mankey_169275C_2CC.bin"
sMankeyAngryPal:
.incbin "graphics/kao/mankey_1692A28_40.bin"
sMankeyAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/mankey_1692A6D_2EB.bin"
sPortraitsMankey:
kao_portrait sMankeyNormalPal, sMankeyNormalGfx
kao_portrait sMankeyAngryPal, sMankeyAngryGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
