.global gKaoMedicham
gKaoMedicham:
kao_siro sPortraitsMedicham
sMedichamNormalPal:
.incbin "graphics/kao/medicham_16B6000_40.bin"
sMedichamNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/medicham_16B6045_297.bin"
sMedichamHappyPal:
.incbin "graphics/kao/medicham_16B62DC_40.bin"
sMedichamHappyGfx:
.incbin "graphics/kao/medicham_16B631C_2A8.bin"
sMedichamPainedPal:
.incbin "graphics/kao/medicham_16B65C4_40.bin"
sMedichamPainedGfx:
.string "AT4PX"
.incbin "graphics/kao/medicham_16B6609_2C3.bin"
sMedichamAngryPal:
.incbin "graphics/kao/medicham_16B68CC_40.bin"
sMedichamAngryGfx:
.incbin "graphics/kao/medicham_16B690C_290.bin"
sMedichamWorriedPal:
.incbin "graphics/kao/medicham_16B6B9C_40.bin"
sMedichamWorriedGfx:
.incbin "graphics/kao/medicham_16B6BDC_290.bin"
sMedichamSadPal:
.incbin "graphics/kao/medicham_16B6E6C_40.bin"
sMedichamSadGfx:
.incbin "graphics/kao/medicham_16B6EAC_28C.bin"
sMedichamCryingPal:
.incbin "graphics/kao/medicham_16B7138_40.bin"
sMedichamCryingGfx:
.incbin "graphics/kao/medicham_16B7178_284.bin"
sPortraitsMedicham:
kao_portrait sMedichamNormalPal, sMedichamNormalGfx
kao_portrait sMedichamHappyPal, sMedichamHappyGfx
kao_portrait sMedichamPainedPal, sMedichamPainedGfx
kao_portrait sMedichamAngryPal, sMedichamAngryGfx
kao_portrait sMedichamWorriedPal, sMedichamWorriedGfx
kao_portrait sMedichamSadPal, sMedichamSadGfx
kao_portrait sMedichamCryingPal, sMedichamCryingGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
