.global gKaoMeowth
gKaoMeowth:
kao_siro sPortraitsMeowth
sMeowthNormalPal:
.incbin "graphics/kao/meowth_168D634_40.bin"
sMeowthNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/meowth_168D679_2CF.bin"
sMeowthHappyPal:
.incbin "graphics/kao/meowth_168D948_40.bin"
sMeowthHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/meowth_168D98D_2DF.bin"
sMeowthPainedPal:
.incbin "graphics/kao/meowth_168DC6C_40.bin"
sMeowthPainedGfx:
.incbin "graphics/kao/meowth_168DCAC_2E8.bin"
sMeowthAngryPal:
.incbin "graphics/kao/meowth_168DF94_40.bin"
sMeowthAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/meowth_168DFD9_2F3.bin"
sMeowthWorriedPal:
.incbin "graphics/kao/meowth_168E2CC_40.bin"
sMeowthWorriedGfx:
.incbin "graphics/kao/meowth_168E30C_2BC.bin"
sMeowthSadPal:
.incbin "graphics/kao/meowth_168E5C8_40.bin"
sMeowthSadGfx:
.incbin "graphics/kao/meowth_168E608_2D0.bin"
sMeowthCryingPal:
.incbin "graphics/kao/meowth_168E8D8_40.bin"
sMeowthCryingGfx:
.incbin "graphics/kao/meowth_168E918_2A8.bin"
sMeowthShoutingPal:
.incbin "graphics/kao/meowth_168EBC0_40.bin"
sMeowthShoutingGfx:
.incbin "graphics/kao/meowth_168EC00_2F0.bin"
sMeowthTearyEyePal:
.incbin "graphics/kao/meowth_168EEF0_40.bin"
sMeowthTearyEyeGfx:
.string "AT4PX"
.incbin "graphics/kao/meowth_168EF35_2AB.bin"
sMeowthDeterminedPal:
.incbin "graphics/kao/meowth_168F1E0_40.bin"
sMeowthDeterminedGfx:
.string "AT4PX"
.incbin "graphics/kao/meowth_168F225_2D3.bin"
sMeowthJoyousPal:
.incbin "graphics/kao/meowth_168F4F8_40.bin"
sMeowthJoyousGfx:
.incbin "graphics/kao/meowth_168F538_2CC.bin"
sMeowthInspiredPal:
.incbin "graphics/kao/meowth_168F804_40.bin"
sMeowthInspiredGfx:
.incbin "graphics/kao/meowth_168F844_2D4.bin"
sMeowthSurprisedPal:
.incbin "graphics/kao/meowth_168FB18_40.bin"
sMeowthSurprisedGfx:
.incbin "graphics/kao/meowth_168FB58_2F8.bin"
sPortraitsMeowth:
kao_portrait sMeowthNormalPal, sMeowthNormalGfx
kao_portrait sMeowthHappyPal, sMeowthHappyGfx
kao_portrait sMeowthPainedPal, sMeowthPainedGfx
kao_portrait sMeowthAngryPal, sMeowthAngryGfx
kao_portrait sMeowthWorriedPal, sMeowthWorriedGfx
kao_portrait sMeowthSadPal, sMeowthSadGfx
kao_portrait sMeowthCryingPal, sMeowthCryingGfx
kao_portrait sMeowthShoutingPal, sMeowthShoutingGfx
kao_portrait sMeowthTearyEyePal, sMeowthTearyEyeGfx
kao_portrait sMeowthDeterminedPal, sMeowthDeterminedGfx
kao_portrait sMeowthJoyousPal, sMeowthJoyousGfx
kao_portrait sMeowthInspiredPal, sMeowthInspiredGfx
kao_portrait sMeowthSurprisedPal, sMeowthSurprisedGfx
