.global gKaoMetapod
gKaoMetapod:
kao_siro sPortraitsMetapod
sMetapodNormalPal:
.incbin "graphics/kao/metapod_16893DC_40.bin"
sMetapodNormalGfx:
.incbin "graphics/kao/metapod_168941C_298.bin"
sPortraitsMetapod:
kao_portrait sMetapodNormalPal, sMetapodNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
