.global gKaoMewtwo
gKaoMewtwo:
kao_siro sPortraitsMewtwo
sMewtwoNormalPal:
.incbin "graphics/kao/mewtwo_169E1C8_40.bin"
sMewtwoNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/mewtwo_169E20D_2AF.bin"
sPortraitsMewtwo:
kao_portrait sMewtwoNormalPal, sMewtwoNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
