.global gKaoMoltres
gKaoMoltres:
kao_siro sPortraitsMoltres
sMoltresNormalPal:
.incbin "graphics/kao/moltres_169DE14_40.bin"
sMoltresNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/moltres_169DE59_2F7.bin"
sPortraitsMoltres:
kao_portrait sMoltresNormalPal, sMoltresNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
