.global gKaoMudkip
gKaoMudkip:
kao_siro sPortraitsMudkip
sMudkipNormalPal:
.incbin "graphics/kao/mudkip_16AE1D4_40.bin"
sMudkipNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/mudkip_16AE219_27B.bin"
sMudkipHappyPal:
.incbin "graphics/kao/mudkip_16AE494_40.bin"
sMudkipHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/mudkip_16AE4D9_25B.bin"
sMudkipPainedPal:
.incbin "graphics/kao/mudkip_16AE734_40.bin"
sMudkipPainedGfx:
.string "AT4PX"
.incbin "graphics/kao/mudkip_16AE779_287.bin"
sMudkipAngryPal:
.incbin "graphics/kao/mudkip_16AEA00_40.bin"
sMudkipAngryGfx:
.incbin "graphics/kao/mudkip_16AEA40_2B8.bin"
sMudkipWorriedPal:
.incbin "graphics/kao/mudkip_16AECF8_40.bin"
sMudkipWorriedGfx:
.incbin "graphics/kao/mudkip_16AED38_2A0.bin"
sMudkipSadPal:
.incbin "graphics/kao/mudkip_16AEFD8_40.bin"
sMudkipSadGfx:
.incbin "graphics/kao/mudkip_16AF018_278.bin"
sMudkipCryingPal:
.incbin "graphics/kao/mudkip_16AF290_40.bin"
sMudkipCryingGfx:
.string "AT4PX"
.incbin "graphics/kao/mudkip_16AF2D5_27B.bin"
sMudkipShoutingPal:
.incbin "graphics/kao/mudkip_16AF550_40.bin"
sMudkipShoutingGfx:
.string "AT4PX"
.incbin "graphics/kao/mudkip_16AF595_2BB.bin"
sMudkipTearyEyePal:
.incbin "graphics/kao/mudkip_16AF850_40.bin"
sMudkipTearyEyeGfx:
.string "AT4PX"
.incbin "graphics/kao/mudkip_16AF895_27F.bin"
sMudkipDeterminedPal:
.incbin "graphics/kao/mudkip_16AFB14_40.bin"
sMudkipDeterminedGfx:
.incbin "graphics/kao/mudkip_16AFB54_254.bin"
sMudkipJoyousPal:
.incbin "graphics/kao/mudkip_16AFDA8_40.bin"
sMudkipJoyousGfx:
.incbin "graphics/kao/mudkip_16AFDE8_2C8.bin"
sMudkipInspiredPal:
.incbin "graphics/kao/mudkip_16B00B0_40.bin"
sMudkipInspiredGfx:
.string "AT4PX"
.incbin "graphics/kao/mudkip_16B00F5_267.bin"
sMudkipSurprisedPal:
.incbin "graphics/kao/mudkip_16B035C_40.bin"
sMudkipSurprisedGfx:
.incbin "graphics/kao/mudkip_16B039C_2B0.bin"
sPortraitsMudkip:
kao_portrait sMudkipNormalPal, sMudkipNormalGfx
kao_portrait sMudkipHappyPal, sMudkipHappyGfx
kao_portrait sMudkipPainedPal, sMudkipPainedGfx
kao_portrait sMudkipAngryPal, sMudkipAngryGfx
kao_portrait sMudkipWorriedPal, sMudkipWorriedGfx
kao_portrait sMudkipSadPal, sMudkipSadGfx
kao_portrait sMudkipCryingPal, sMudkipCryingGfx
kao_portrait sMudkipShoutingPal, sMudkipShoutingGfx
kao_portrait sMudkipTearyEyePal, sMudkipTearyEyeGfx
kao_portrait sMudkipDeterminedPal, sMudkipDeterminedGfx
kao_portrait sMudkipJoyousPal, sMudkipJoyousGfx
kao_portrait sMudkipInspiredPal, sMudkipInspiredGfx
kao_portrait sMudkipSurprisedPal, sMudkipSurprisedGfx
