.global gKaoMunchlax
gKaoMunchlax:
kao_siro sPortraitsMunchlax
sMunchlaxNormalPal:
.incbin "graphics/kao/munchlax_16BBEF8_40.bin"
sMunchlaxNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/munchlax_16BBF3D_293.bin"
sMunchlax1Pal:
.incbin "graphics/kao/munchlax_16BC1D0_40.bin"
sMunchlax1Gfx:
.string "AT4PX"
.incbin "graphics/kao/munchlax_16BC215_2A3.bin"
sMunchlax2Pal:
.incbin "graphics/kao/munchlax_16BC4B8_40.bin"
sMunchlax2Gfx:
.string "AT4PX"
.incbin "graphics/kao/munchlax_16BC4FD_2BF.bin"
sMunchlax3Pal:
.incbin "graphics/kao/munchlax_16BC7BC_40.bin"
sMunchlax3Gfx:
.incbin "graphics/kao/munchlax_16BC7FC_284.bin"
sMunchlax4Pal:
.incbin "graphics/kao/munchlax_16BCA80_40.bin"
sMunchlax4Gfx:
.string "AT4PX"
.incbin "graphics/kao/munchlax_16BCAC5_2AB.bin"
sMunchlax5Pal:
.incbin "graphics/kao/munchlax_16BCD70_40.bin"
sMunchlax5Gfx:
.string "AT4PX"
.incbin "graphics/kao/munchlax_16BCDB5_287.bin"
sPortraitsMunchlax:
kao_portrait sMunchlaxNormalPal, sMunchlaxNormalGfx
kao_portrait sMunchlax1Pal, sMunchlax1Gfx
kao_portrait sMunchlax2Pal, sMunchlax2Gfx
kao_portrait sMunchlax3Pal, sMunchlax3Gfx
kao_portrait sMunchlax4Pal, sMunchlax4Gfx
kao_portrait sMunchlax5Pal, sMunchlax5Gfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
