.global gKaoNinetales
gKaoNinetales:
kao_siro sPortraitsNinetales
sNinetalesNormalPal:
.incbin "graphics/kao/ninetales_168C748_40.bin"
sNinetalesNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/ninetales_168C78D_2B7.bin"
sPortraitsNinetales:
kao_portrait sNinetalesNormalPal, sNinetalesNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
