.global gKaoOctillery
gKaoOctillery:
kao_siro sPortraitsOctillery
sOctilleryNormalPal:
.incbin "graphics/kao/octillery_16A72CC_40.bin"
sOctilleryNormalGfx:
.incbin "graphics/kao/octillery_16A730C_2C4.bin"
sPortraitsOctillery:
kao_portrait sOctilleryNormalPal, sOctilleryNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
