.global gKaoPelipper
gKaoPelipper:
kao_siro sPortraitsPelipper
sPelipperNormalPal:
.incbin "graphics/kao/pelipper_16B2A58_40.bin"
sPelipperNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/pelipper_16B2A9D_21F.bin"
sPortraitsPelipper:
kao_portrait sPelipperNormalPal, sPelipperNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
