.global gKaoPersian
gKaoPersian:
kao_siro sPortraitsPersian
sPersianNormalPal:
.incbin "graphics/kao/persian_168FEC8_40.bin"
sPersianNormalGfx:
.incbin "graphics/kao/persian_168FF08_2B4.bin"
sPortraitsPersian:
kao_portrait sPersianNormalPal, sPersianNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
