.global gKaoPikachu
gKaoPikachu:
kao_siro sPortraitsPikachu
sPikachuNormalPal:
.incbin "graphics/kao/pikachu_168A34C_40.bin"
sPikachuNormalGfx:
.incbin "graphics/kao/pikachu_168A38C_260.bin"
sPikachuHappyPal:
.incbin "graphics/kao/pikachu_168A5EC_40.bin"
sPikachuHappyGfx:
.incbin "graphics/kao/pikachu_168A62C_274.bin"
sPikachuPainedPal:
.incbin "graphics/kao/pikachu_168A8A0_40.bin"
sPikachuPainedGfx:
.string "AT4PX"
.incbin "graphics/kao/pikachu_168A8E5_263.bin"
sPikachuAngryPal:
.incbin "graphics/kao/pikachu_168AB48_40.bin"
sPikachuAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/pikachu_168AB8D_2AB.bin"
sPikachuWorriedPal:
.incbin "graphics/kao/pikachu_168AE38_40.bin"
sPikachuWorriedGfx:
.incbin "graphics/kao/pikachu_168AE78_260.bin"
sPikachuSadPal:
.incbin "graphics/kao/pikachu_168B0D8_40.bin"
sPikachuSadGfx:
.incbin "graphics/kao/pikachu_168B118_254.bin"
sPikachuCryingPal:
.incbin "graphics/kao/pikachu_168B36C_40.bin"
sPikachuCryingGfx:
.incbin "graphics/kao/pikachu_168B3AC_2A4.bin"
sPikachuShoutingPal:
.incbin "graphics/kao/pikachu_168B650_40.bin"
sPikachuShoutingGfx:
.string "AT4PX"
.incbin "graphics/kao/pikachu_168B695_293.bin"
sPikachuTearyEyePal:
.incbin "graphics/kao/pikachu_168B928_40.bin"
sPikachuTearyEyeGfx:
.incbin "graphics/kao/pikachu_168B968_274.bin"
sPikachuDeterminedPal:
.incbin "graphics/kao/pikachu_168BBDC_40.bin"
sPikachuDeterminedGfx:
.incbin "graphics/kao/pikachu_168BC1C_244.bin"
sPikachuJoyousPal:
.incbin "graphics/kao/pikachu_168BE60_40.bin"
sPikachuJoyousGfx:
.string "AT4PX"
.incbin "graphics/kao/pikachu_168BEA5_2A3.bin"
sPikachuInspiredPal:
.incbin "graphics/kao/pikachu_168C148_40.bin"
sPikachuInspiredGfx:
.incbin "graphics/kao/pikachu_168C188_26C.bin"
sPikachuSurprisedPal:
.incbin "graphics/kao/pikachu_168C3F4_40.bin"
sPikachuSurprisedGfx:
.incbin "graphics/kao/pikachu_168C434_29C.bin"
sPortraitsPikachu:
kao_portrait sPikachuNormalPal, sPikachuNormalGfx
kao_portrait sPikachuHappyPal, sPikachuHappyGfx
kao_portrait sPikachuPainedPal, sPikachuPainedGfx
kao_portrait sPikachuAngryPal, sPikachuAngryGfx
kao_portrait sPikachuWorriedPal, sPikachuWorriedGfx
kao_portrait sPikachuSadPal, sPikachuSadGfx
kao_portrait sPikachuCryingPal, sPikachuCryingGfx
kao_portrait sPikachuShoutingPal, sPikachuShoutingGfx
kao_portrait sPikachuTearyEyePal, sPikachuTearyEyeGfx
kao_portrait sPikachuDeterminedPal, sPikachuDeterminedGfx
kao_portrait sPikachuJoyousPal, sPikachuJoyousGfx
kao_portrait sPikachuInspiredPal, sPikachuInspiredGfx
kao_portrait sPikachuSurprisedPal, sPikachuSurprisedGfx
