.global gKaoPsyduck
gKaoPsyduck:
kao_siro sPortraitsPsyduck
sPsyduckNormalPal:
.incbin "graphics/kao/psyduck_1690234_40.bin"
sPsyduckNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/psyduck_1690279_277.bin"
sPsyduckHappyPal:
.incbin "graphics/kao/psyduck_16904F0_40.bin"
sPsyduckHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/psyduck_1690535_277.bin"
sPsyduckPainedPal:
.incbin "graphics/kao/psyduck_16907AC_40.bin"
sPsyduckPainedGfx:
.incbin "graphics/kao/psyduck_16907EC_280.bin"
sPsyduckAngryPal:
.incbin "graphics/kao/psyduck_1690A6C_40.bin"
sPsyduckAngryGfx:
.incbin "graphics/kao/psyduck_1690AAC_284.bin"
sPsyduckWorriedPal:
.incbin "graphics/kao/psyduck_1690D30_40.bin"
sPsyduckWorriedGfx:
.string "AT4PX"
.incbin "graphics/kao/psyduck_1690D75_267.bin"
sPsyduckSadPal:
.incbin "graphics/kao/psyduck_1690FDC_40.bin"
sPsyduckSadGfx:
.incbin "graphics/kao/psyduck_169101C_290.bin"
sPsyduckCryingPal:
.incbin "graphics/kao/psyduck_16912AC_40.bin"
sPsyduckCryingGfx:
.incbin "graphics/kao/psyduck_16912EC_288.bin"
sPsyduckShoutingPal:
.incbin "graphics/kao/psyduck_1691574_40.bin"
sPsyduckShoutingGfx:
.incbin "graphics/kao/psyduck_16915B4_28C.bin"
sPsyduckTearyEyePal:
.incbin "graphics/kao/psyduck_1691840_40.bin"
sPsyduckTearyEyeGfx:
.string "AT4PX"
.incbin "graphics/kao/psyduck_1691885_287.bin"
sPsyduckDeterminedPal:
.incbin "graphics/kao/psyduck_1691B0C_40.bin"
sPsyduckDeterminedGfx:
.incbin "graphics/kao/psyduck_1691B4C_28C.bin"
sPsyduckJoyousPal:
.incbin "graphics/kao/psyduck_1691DD8_40.bin"
sPsyduckJoyousGfx:
.incbin "graphics/kao/psyduck_1691E18_2CC.bin"
sPsyduckInspiredPal:
.incbin "graphics/kao/psyduck_16920E4_40.bin"
sPsyduckInspiredGfx:
.incbin "graphics/kao/psyduck_1692124_29C.bin"
sPsyduckSurprisedPal:
.incbin "graphics/kao/psyduck_16923C0_40.bin"
sPsyduckSurprisedGfx:
.string "AT4PX"
.incbin "graphics/kao/psyduck_1692405_297.bin"
sPortraitsPsyduck:
kao_portrait sPsyduckNormalPal, sPsyduckNormalGfx
kao_portrait sPsyduckHappyPal, sPsyduckHappyGfx
kao_portrait sPsyduckPainedPal, sPsyduckPainedGfx
kao_portrait sPsyduckAngryPal, sPsyduckAngryGfx
kao_portrait sPsyduckWorriedPal, sPsyduckWorriedGfx
kao_portrait sPsyduckSadPal, sPsyduckSadGfx
kao_portrait sPsyduckCryingPal, sPsyduckCryingGfx
kao_portrait sPsyduckShoutingPal, sPsyduckShoutingGfx
kao_portrait sPsyduckTearyEyePal, sPsyduckTearyEyeGfx
kao_portrait sPsyduckDeterminedPal, sPsyduckDeterminedGfx
kao_portrait sPsyduckJoyousPal, sPsyduckJoyousGfx
kao_portrait sPsyduckInspiredPal, sPsyduckInspiredGfx
kao_portrait sPsyduckSurprisedPal, sPsyduckSurprisedGfx
.incbin "graphics/kao/psyduck_1692704_8.bin"
