.global gKaoRaikou
gKaoRaikou:
kao_siro sPortraitsRaikou
sRaikouNormalPal:
.incbin "graphics/kao/raikou_16A7E5C_40.bin"
sRaikouNormalGfx:
.incbin "graphics/kao/raikou_16A7E9C_2DC.bin"
sPortraitsRaikou:
kao_portrait sRaikouNormalPal, sRaikouNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
