.global gKaoRayquaza
gKaoRayquaza:
kao_siro sPortraitsRayquaza
sRayquazaNormalPal:
.incbin "graphics/kao/rayquaza_16BB274_40.bin"
sRayquazaNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/rayquaza_16BB2B9_2CB.bin"
sPortraitsRayquaza:
kao_portrait sRayquazaNormalPal, sRayquazaNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
