.global gKaoRayquazaCutscene
gKaoRayquazaCutscene:
kao_siro sPortraitsRayquazaCutscene
sRayquazaCutsceneNormalPal:
.incbin "graphics/kao/rayquazacutscene_16BD0B4_40.bin"
sRayquazaCutsceneNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/rayquazacutscene_16BD0F9_2CB.bin"
sPortraitsRayquazaCutscene:
kao_portrait sRayquazaCutsceneNormalPal, sRayquazaCutsceneNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
