.global gKaoShiftry
gKaoShiftry:
kao_siro sPortraitsShiftry
sShiftryNormalPal:
.incbin "graphics/kao/shiftry_16B1D64_40.bin"
sShiftryNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/shiftry_16B1DA9_2D3.bin"
sShiftrySurprisedPal:
.incbin "graphics/kao/shiftry_16B207C_40.bin"
sShiftrySurprisedGfx:
.incbin "graphics/kao/shiftry_16B20BC_2F4.bin"
sShiftryHappyPal:
.incbin "graphics/kao/shiftry_16B23B0_40.bin"
sShiftryHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/shiftry_16B23F5_2CB.bin"
sShiftryAngryPal:
.incbin "graphics/kao/shiftry_16B26C0_40.bin"
sShiftryAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/shiftry_16B2705_2DB.bin"
sPortraitsShiftry:
kao_portrait sShiftryNormalPal, sShiftryNormalGfx
kao_portrait sShiftrySurprisedPal, sShiftrySurprisedGfx
kao_portrait sShiftryHappyPal, sShiftryHappyGfx
kao_portrait sShiftryAngryPal, sShiftryAngryGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
