.global gKaoSkarmory
gKaoSkarmory:
kao_siro sPortraitsSkarmory
sSkarmoryNormalPal:
.incbin "graphics/kao/skarmory_16A7648_40.bin"
sSkarmoryNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/skarmory_16A768D_26B.bin"
sSkarmoryPlaceholderPal:
.incbin "graphics/kao/skarmory_16A78F8_40.bin"
sSkarmoryPlaceholderGfx:
.string "AT4PX"
.incbin "graphics/kao/skarmory_16A793D_127.bin"
sPortraitsSkarmory:
kao_portrait sSkarmoryNormalPal, sSkarmoryNormalGfx
kao_portrait sSkarmoryPlaceholderPal, sSkarmoryPlaceholderGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
