.global gKaoSkitty
gKaoSkitty:
kao_siro sPortraitsSkitty
sSkittyNormalPal:
.incbin "graphics/kao/skitty_16B3980_40.bin"
sSkittyNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/skitty_16B39C5_28B.bin"
sSkittyHappyPal:
.incbin "graphics/kao/skitty_16B3C50_40.bin"
sSkittyHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/skitty_16B3C95_2A3.bin"
sSkittyPainedPal:
.incbin "graphics/kao/skitty_16B3F38_40.bin"
sSkittyPainedGfx:
.string "AT4PX"
.incbin "graphics/kao/skitty_16B3F7D_29B.bin"
sSkittyAngryPal:
.incbin "graphics/kao/skitty_16B4218_40.bin"
sSkittyAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/skitty_16B425D_2A3.bin"
sSkittyWorriedPal:
.incbin "graphics/kao/skitty_16B4500_40.bin"
sSkittyWorriedGfx:
.string "AT4PX"
.incbin "graphics/kao/skitty_16B4545_29F.bin"
sSkittySadPal:
.incbin "graphics/kao/skitty_16B47E4_40.bin"
sSkittySadGfx:
.incbin "graphics/kao/skitty_16B4824_2AC.bin"
sSkittyCryingPal:
.incbin "graphics/kao/skitty_16B4AD0_40.bin"
sSkittyCryingGfx:
.string "AT4PX"
.incbin "graphics/kao/skitty_16B4B15_29B.bin"
sSkittyShoutingPal:
.incbin "graphics/kao/skitty_16B4DB0_40.bin"
sSkittyShoutingGfx:
.string "AT4PX"
.incbin "graphics/kao/skitty_16B4DF5_2E3.bin"
sSkittyTearyEyePal:
.incbin "graphics/kao/skitty_16B50D8_40.bin"
sSkittyTearyEyeGfx:
.incbin "graphics/kao/skitty_16B5118_298.bin"
sSkittyDeterminedPal:
.incbin "graphics/kao/skitty_16B53B0_40.bin"
sSkittyDeterminedGfx:
.string "AT4PX"
.incbin "graphics/kao/skitty_16B53F5_2A7.bin"
sSkittyJoyousPal:
.incbin "graphics/kao/skitty_16B569C_40.bin"
sSkittyJoyousGfx:
.incbin "graphics/kao/skitty_16B56DC_2B4.bin"
sSkittyInspiredPal:
.incbin "graphics/kao/skitty_16B5990_40.bin"
sSkittyInspiredGfx:
.string "AT4PX"
.incbin "graphics/kao/skitty_16B59D5_297.bin"
sSkittySurprisedPal:
.incbin "graphics/kao/skitty_16B5C6C_40.bin"
sSkittySurprisedGfx:
.incbin "graphics/kao/skitty_16B5CAC_2D4.bin"
sPortraitsSkitty:
kao_portrait sSkittyNormalPal, sSkittyNormalGfx
kao_portrait sSkittyHappyPal, sSkittyHappyGfx
kao_portrait sSkittyPainedPal, sSkittyPainedGfx
kao_portrait sSkittyAngryPal, sSkittyAngryGfx
kao_portrait sSkittyWorriedPal, sSkittyWorriedGfx
kao_portrait sSkittySadPal, sSkittySadGfx
kao_portrait sSkittyCryingPal, sSkittyCryingGfx
kao_portrait sSkittyShoutingPal, sSkittyShoutingGfx
kao_portrait sSkittyTearyEyePal, sSkittyTearyEyeGfx
kao_portrait sSkittyDeterminedPal, sSkittyDeterminedGfx
kao_portrait sSkittyJoyousPal, sSkittyJoyousGfx
kao_portrait sSkittyInspiredPal, sSkittyInspiredGfx
kao_portrait sSkittySurprisedPal, sSkittySurprisedGfx
.incbin "graphics/kao/skitty_16B5FE8_8.bin"
