.global gKaoSmeargle
gKaoSmeargle:
kao_siro sPortraitsSmeargle
sSmeargleNormalPal:
.incbin "graphics/kao/smeargle_16A7ADC_40.bin"
sSmeargleNormalGfx:
.incbin "graphics/kao/smeargle_16A7B1C_2C8.bin"
sPortraitsSmeargle:
kao_portrait sSmeargleNormalPal, sSmeargleNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
