.global gKaoSnubbull
gKaoSnubbull:
kao_siro sPortraitsSnubbull
sSnubbullNormalPal:
.incbin "graphics/kao/snubbull_16A6570_40.bin"
sSnubbullNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/snubbull_16A65B5_2B7.bin"
sSnubbullHappyPal:
.incbin "graphics/kao/snubbull_16A686C_40.bin"
sSnubbullHappyGfx:
.incbin "graphics/kao/snubbull_16A68AC_2F8.bin"
sSnubbullPainedPal:
.incbin "graphics/kao/snubbull_16A6BA4_40.bin"
sSnubbullPainedGfx:
.string "AT4PX"
.incbin "graphics/kao/snubbull_16A6BE9_2B7.bin"
sPortraitsSnubbull:
kao_portrait sSnubbullNormalPal, sSnubbullNormalGfx
kao_portrait sSnubbullHappyPal, sSnubbullHappyGfx
kao_portrait sSnubbullPainedPal, sSnubbullPainedGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
