.global gKaoSpinda
gKaoSpinda:
kao_siro sPortraitsSpinda
sSpindaNormalPal:
.incbin "graphics/kao/spinda_16B7744_40.bin"
sSpindaNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/spinda_16B7789_2D3.bin"
sSpindaSadPal:
.incbin "graphics/kao/spinda_16B7A5C_40.bin"
sSpindaSadGfx:
.incbin "graphics/kao/spinda_16B7A9C_288.bin"
sSpindaNormalFlipPal:
.incbin "graphics/kao/spinda_16B7D24_40.bin"
sSpindaNormalFlipGfx:
.string "AT4PX"
.incbin "graphics/kao/spinda_16B7D69_2DB.bin"
sSpindaSadFlipPal:
.incbin "graphics/kao/spinda_16B8044_40.bin"
sSpindaSadFlipGfx:
.string "AT4PX"
.incbin "graphics/kao/spinda_16B8089_28B.bin"
sPortraitsSpinda:
kao_portrait sSpindaNormalPal, sSpindaNormalGfx
kao_portrait sSpindaSadPal, sSpindaSadGfx
kao_portrait sSpindaNormalFlipPal, sSpindaNormalFlipGfx
kao_portrait sSpindaSadFlipPal, sSpindaSadFlipGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
