.global gKaoSquirtle
gKaoSquirtle:
kao_siro sPortraitsSquirtle
sSquirtleNormalPal:
.incbin "graphics/kao/squirtle_16857F8_40.bin"
sSquirtleNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/squirtle_168583D_28F.bin"
sSquirtleHappyPal:
.incbin "graphics/kao/squirtle_1685ACC_40.bin"
sSquirtleHappyGfx:
.incbin "graphics/kao/squirtle_1685B0C_2A4.bin"
sSquirtlePainedPal:
.incbin "graphics/kao/squirtle_1685DB0_40.bin"
sSquirtlePainedGfx:
.string "AT4PX"
.incbin "graphics/kao/squirtle_1685DF5_2A3.bin"
sSquirtleAngryPal:
.incbin "graphics/kao/squirtle_1686098_40.bin"
sSquirtleAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/squirtle_16860DD_2C7.bin"
sSquirtleWorriedPal:
.incbin "graphics/kao/squirtle_16863A4_40.bin"
sSquirtleWorriedGfx:
.incbin "graphics/kao/squirtle_16863E4_2B4.bin"
sSquirtleSadPal:
.incbin "graphics/kao/squirtle_1686698_40.bin"
sSquirtleSadGfx:
.incbin "graphics/kao/squirtle_16866D8_29C.bin"
sSquirtleCryingPal:
.incbin "graphics/kao/squirtle_1686974_40.bin"
sSquirtleCryingGfx:
.incbin "graphics/kao/squirtle_16869B4_2AC.bin"
sSquirtleShoutingPal:
.incbin "graphics/kao/squirtle_1686C60_40.bin"
sSquirtleShoutingGfx:
.string "AT4PX"
.incbin "graphics/kao/squirtle_1686CA5_2A7.bin"
sSquirtleTearyEyePal:
.incbin "graphics/kao/squirtle_1686F4C_40.bin"
sSquirtleTearyEyeGfx:
.incbin "graphics/kao/squirtle_1686F8C_2A0.bin"
sSquirtleDeterminedPal:
.incbin "graphics/kao/squirtle_168722C_40.bin"
sSquirtleDeterminedGfx:
.incbin "graphics/kao/squirtle_168726C_298.bin"
sSquirtleJoyousPal:
.incbin "graphics/kao/squirtle_1687504_40.bin"
sSquirtleJoyousGfx:
.incbin "graphics/kao/squirtle_1687544_2E4.bin"
sSquirtleInspiredPal:
.incbin "graphics/kao/squirtle_1687828_40.bin"
sSquirtleInspiredGfx:
.incbin "graphics/kao/squirtle_1687868_298.bin"
sSquirtleSurprisedPal:
.incbin "graphics/kao/squirtle_1687B00_40.bin"
sSquirtleSurprisedGfx:
.string "AT4PX"
.incbin "graphics/kao/squirtle_1687B45_2CB.bin"
sPortraitsSquirtle:
kao_portrait sSquirtleNormalPal, sSquirtleNormalGfx
kao_portrait sSquirtleHappyPal, sSquirtleHappyGfx
kao_portrait sSquirtlePainedPal, sSquirtlePainedGfx
kao_portrait sSquirtleAngryPal, sSquirtleAngryGfx
kao_portrait sSquirtleWorriedPal, sSquirtleWorriedGfx
kao_portrait sSquirtleSadPal, sSquirtleSadGfx
kao_portrait sSquirtleCryingPal, sSquirtleCryingGfx
kao_portrait sSquirtleShoutingPal, sSquirtleShoutingGfx
kao_portrait sSquirtleTearyEyePal, sSquirtleTearyEyeGfx
kao_portrait sSquirtleDeterminedPal, sSquirtleDeterminedGfx
kao_portrait sSquirtleJoyousPal, sSquirtleJoyousGfx
kao_portrait sSquirtleInspiredPal, sSquirtleInspiredGfx
kao_portrait sSquirtleSurprisedPal, sSquirtleSurprisedGfx
