.global gKaoSuicune
gKaoSuicune:
kao_siro sPortraitsSuicune
sSuicuneNormalPal:
.incbin "graphics/kao/suicune_16A8564_40.bin"
sSuicuneNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/suicune_16A85A9_2F7.bin"
sPortraitsSuicune:
kao_portrait sSuicuneNormalPal, sSuicuneNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
