.global gKaoTorchic
gKaoTorchic:
kao_siro sPortraitsTorchic
sTorchicNormalPal:
.incbin "graphics/kao/torchic_16ABC24_40.bin"
sTorchicNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/torchic_16ABC69_287.bin"
sTorchicHappyPal:
.incbin "graphics/kao/torchic_16ABEF0_40.bin"
sTorchicHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/torchic_16ABF35_2A3.bin"
sTorchicPainedPal:
.incbin "graphics/kao/torchic_16AC1D8_40.bin"
sTorchicPainedGfx:
.string "AT4PX"
.incbin "graphics/kao/torchic_16AC21D_2B3.bin"
sTorchicAngryPal:
.incbin "graphics/kao/torchic_16AC4D0_40.bin"
sTorchicAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/torchic_16AC515_293.bin"
sTorchicWorriedPal:
.incbin "graphics/kao/torchic_16AC7A8_40.bin"
sTorchicWorriedGfx:
.incbin "graphics/kao/torchic_16AC7E8_260.bin"
sTorchicSadPal:
.incbin "graphics/kao/torchic_16ACA48_40.bin"
sTorchicSadGfx:
.incbin "graphics/kao/torchic_16ACA88_290.bin"
sTorchicCryingPal:
.incbin "graphics/kao/torchic_16ACD18_40.bin"
sTorchicCryingGfx:
.incbin "graphics/kao/torchic_16ACD58_28C.bin"
sTorchicShoutingPal:
.incbin "graphics/kao/torchic_16ACFE4_40.bin"
sTorchicShoutingGfx:
.incbin "graphics/kao/torchic_16AD024_2D4.bin"
sTorchicTearyEyePal:
.incbin "graphics/kao/torchic_16AD2F8_40.bin"
sTorchicTearyEyeGfx:
.incbin "graphics/kao/torchic_16AD338_29C.bin"
sTorchicDeterminedPal:
.incbin "graphics/kao/torchic_16AD5D4_40.bin"
sTorchicDeterminedGfx:
.incbin "graphics/kao/torchic_16AD614_29C.bin"
sTorchicJoyousPal:
.incbin "graphics/kao/torchic_16AD8B0_40.bin"
sTorchicJoyousGfx:
.string "AT4PX"
.incbin "graphics/kao/torchic_16AD8F5_29F.bin"
sTorchicInspiredPal:
.incbin "graphics/kao/torchic_16ADB94_40.bin"
sTorchicInspiredGfx:
.incbin "graphics/kao/torchic_16ADBD4_288.bin"
sTorchicSurprisedPal:
.incbin "graphics/kao/torchic_16ADE5C_40.bin"
sTorchicSurprisedGfx:
.incbin "graphics/kao/torchic_16ADE9C_2C0.bin"
sPortraitsTorchic:
kao_portrait sTorchicNormalPal, sTorchicNormalGfx
kao_portrait sTorchicHappyPal, sTorchicHappyGfx
kao_portrait sTorchicPainedPal, sTorchicPainedGfx
kao_portrait sTorchicAngryPal, sTorchicAngryGfx
kao_portrait sTorchicWorriedPal, sTorchicWorriedGfx
kao_portrait sTorchicSadPal, sTorchicSadGfx
kao_portrait sTorchicCryingPal, sTorchicCryingGfx
kao_portrait sTorchicShoutingPal, sTorchicShoutingGfx
kao_portrait sTorchicTearyEyePal, sTorchicTearyEyeGfx
kao_portrait sTorchicDeterminedPal, sTorchicDeterminedGfx
kao_portrait sTorchicJoyousPal, sTorchicJoyousGfx
kao_portrait sTorchicInspiredPal, sTorchicInspiredGfx
kao_portrait sTorchicSurprisedPal, sTorchicSurprisedGfx
