.global gKaoTotodile
gKaoTotodile:
kao_siro sPortraitsTotodile
sTotodileNormalPal:
.incbin "graphics/kao/totodile_16A2F6C_40.bin"
sTotodileNormalGfx:
.incbin "graphics/kao/totodile_16A2FAC_2A0.bin"
sTotodileHappyPal:
.incbin "graphics/kao/totodile_16A324C_40.bin"
sTotodileHappyGfx:
.incbin "graphics/kao/totodile_16A328C_29C.bin"
sTotodilePainedPal:
.incbin "graphics/kao/totodile_16A3528_40.bin"
sTotodilePainedGfx:
.string "AT4PX"
.incbin "graphics/kao/totodile_16A356D_2A7.bin"
sTotodileAngryPal:
.incbin "graphics/kao/totodile_16A3814_40.bin"
sTotodileAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/totodile_16A3859_2A7.bin"
sTotodileWorriedPal:
.incbin "graphics/kao/totodile_16A3B00_40.bin"
sTotodileWorriedGfx:
.string "AT4PX"
.incbin "graphics/kao/totodile_16A3B45_293.bin"
sTotodileSadPal:
.incbin "graphics/kao/totodile_16A3DD8_40.bin"
sTotodileSadGfx:
.incbin "graphics/kao/totodile_16A3E18_2AC.bin"
sTotodileCryingPal:
.incbin "graphics/kao/totodile_16A40C4_40.bin"
sTotodileCryingGfx:
.incbin "graphics/kao/totodile_16A4104_2DC.bin"
sTotodileShoutingPal:
.incbin "graphics/kao/totodile_16A43E0_40.bin"
sTotodileShoutingGfx:
.string "AT4PX"
.incbin "graphics/kao/totodile_16A4425_2D3.bin"
sTotodileTearyEyePal:
.incbin "graphics/kao/totodile_16A46F8_40.bin"
sTotodileTearyEyeGfx:
.incbin "graphics/kao/totodile_16A4738_2A8.bin"
sTotodileDeterminedPal:
.incbin "graphics/kao/totodile_16A49E0_40.bin"
sTotodileDeterminedGfx:
.string "AT4PX"
.incbin "graphics/kao/totodile_16A4A25_2A3.bin"
sTotodileJoyousPal:
.incbin "graphics/kao/totodile_16A4CC8_40.bin"
sTotodileJoyousGfx:
.incbin "graphics/kao/totodile_16A4D08_2F0.bin"
sTotodileInspiredPal:
.incbin "graphics/kao/totodile_16A4FF8_40.bin"
sTotodileInspiredGfx:
.incbin "graphics/kao/totodile_16A5038_29C.bin"
sTotodileSurprisedPal:
.incbin "graphics/kao/totodile_16A52D4_40.bin"
sTotodileSurprisedGfx:
.incbin "graphics/kao/totodile_16A5314_2D8.bin"
sPortraitsTotodile:
kao_portrait sTotodileNormalPal, sTotodileNormalGfx
kao_portrait sTotodileHappyPal, sTotodileHappyGfx
kao_portrait sTotodilePainedPal, sTotodilePainedGfx
kao_portrait sTotodileAngryPal, sTotodileAngryGfx
kao_portrait sTotodileWorriedPal, sTotodileWorriedGfx
kao_portrait sTotodileSadPal, sTotodileSadGfx
kao_portrait sTotodileCryingPal, sTotodileCryingGfx
kao_portrait sTotodileShoutingPal, sTotodileShoutingGfx
kao_portrait sTotodileTearyEyePal, sTotodileTearyEyeGfx
kao_portrait sTotodileDeterminedPal, sTotodileDeterminedGfx
kao_portrait sTotodileJoyousPal, sTotodileJoyousGfx
kao_portrait sTotodileInspiredPal, sTotodileInspiredGfx
kao_portrait sTotodileSurprisedPal, sTotodileSurprisedGfx
