.global gKaoTreecko
gKaoTreecko:
kao_siro sPortraitsTreecko
sTreeckoNormalPal:
.incbin "graphics/kao/treecko_16A9614_40.bin"
sTreeckoNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/treecko_16A9659_28F.bin"
sTreeckoHappyPal:
.incbin "graphics/kao/treecko_16A98E8_40.bin"
sTreeckoHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/treecko_16A992D_27F.bin"
sTreeckoPainedPal:
.incbin "graphics/kao/treecko_16A9BAC_40.bin"
sTreeckoPainedGfx:
.incbin "graphics/kao/treecko_16A9BEC_2A4.bin"
sTreeckoAngryPal:
.incbin "graphics/kao/treecko_16A9E90_40.bin"
sTreeckoAngryGfx:
.string "AT4PX"
.incbin "graphics/kao/treecko_16A9ED5_2A3.bin"
sTreeckoWorriedPal:
.incbin "graphics/kao/treecko_16AA178_40.bin"
sTreeckoWorriedGfx:
.incbin "graphics/kao/treecko_16AA1B8_298.bin"
sTreeckoSadPal:
.incbin "graphics/kao/treecko_16AA450_40.bin"
sTreeckoSadGfx:
.string "AT4PX"
.incbin "graphics/kao/treecko_16AA495_28B.bin"
sTreeckoCryingPal:
.incbin "graphics/kao/treecko_16AA720_40.bin"
sTreeckoCryingGfx:
.string "AT4PX"
.incbin "graphics/kao/treecko_16AA765_287.bin"
sTreeckoShoutingPal:
.incbin "graphics/kao/treecko_16AA9EC_40.bin"
sTreeckoShoutingGfx:
.incbin "graphics/kao/treecko_16AAA2C_2BC.bin"
sTreeckoTearyEyePal:
.incbin "graphics/kao/treecko_16AACE8_40.bin"
sTreeckoTearyEyeGfx:
.incbin "graphics/kao/treecko_16AAD28_29C.bin"
sTreeckoDeterminedPal:
.incbin "graphics/kao/treecko_16AAFC4_40.bin"
sTreeckoDeterminedGfx:
.incbin "graphics/kao/treecko_16AB004_27C.bin"
sTreeckoJoyousPal:
.incbin "graphics/kao/treecko_16AB280_40.bin"
sTreeckoJoyousGfx:
.string "AT4PX"
.incbin "graphics/kao/treecko_16AB2C5_2EF.bin"
sTreeckoInspiredPal:
.incbin "graphics/kao/treecko_16AB5B4_40.bin"
sTreeckoInspiredGfx:
.incbin "graphics/kao/treecko_16AB5F4_2A4.bin"
sTreeckoSurprisedPal:
.incbin "graphics/kao/treecko_16AB898_40.bin"
sTreeckoSurprisedGfx:
.incbin "graphics/kao/treecko_16AB8D8_2D4.bin"
sPortraitsTreecko:
kao_portrait sTreeckoNormalPal, sTreeckoNormalGfx
kao_portrait sTreeckoHappyPal, sTreeckoHappyGfx
kao_portrait sTreeckoPainedPal, sTreeckoPainedGfx
kao_portrait sTreeckoAngryPal, sTreeckoAngryGfx
kao_portrait sTreeckoWorriedPal, sTreeckoWorriedGfx
kao_portrait sTreeckoSadPal, sTreeckoSadGfx
kao_portrait sTreeckoCryingPal, sTreeckoCryingGfx
kao_portrait sTreeckoShoutingPal, sTreeckoShoutingGfx
kao_portrait sTreeckoTearyEyePal, sTreeckoTearyEyeGfx
kao_portrait sTreeckoDeterminedPal, sTreeckoDeterminedGfx
kao_portrait sTreeckoJoyousPal, sTreeckoJoyousGfx
kao_portrait sTreeckoInspiredPal, sTreeckoInspiredGfx
kao_portrait sTreeckoSurprisedPal, sTreeckoSurprisedGfx
