.global gKaoTyranitar
gKaoTyranitar:
kao_siro sPortraitsTyranitar
sTyranitarNormalPal:
.incbin "graphics/kao/tyranitar_16A8918_40.bin"
sTyranitarNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/tyranitar_16A895D_263.bin"
sTyranitarSurprisedPal:
.incbin "graphics/kao/tyranitar_16A8BC0_40.bin"
sTyranitarSurprisedGfx:
.string "AT4PX"
.incbin "graphics/kao/tyranitar_16A8C05_2C7.bin"
sPortraitsTyranitar:
kao_portrait sTyranitarNormalPal, sTyranitarNormalGfx
kao_portrait sTyranitarSurprisedPal, sTyranitarSurprisedGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
