.global gKaoWhiscash
gKaoWhiscash:
kao_siro sPortraitsWhiscash
sWhiscashNormalPal:
.incbin "graphics/kao/whiscash_16B838C_40.bin"
sWhiscashNormalGfx:
.incbin "graphics/kao/whiscash_16B83CC_27C.bin"
sWhiscashHappyPal:
.incbin "graphics/kao/whiscash_16B8648_40.bin"
sWhiscashHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/whiscash_16B868D_25B.bin"
sPortraitsWhiscash:
kao_portrait sWhiscashNormalPal, sWhiscashNormalGfx
kao_portrait sWhiscashHappyPal, sWhiscashHappyGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
