.global gKaoWigglytuff
gKaoWigglytuff:
kao_siro sPortraitsWigglytuff
sWigglytuffNormalPal:
.incbin "graphics/kao/wigglytuff_168CABC_40.bin"
sWigglytuffNormalGfx:
.incbin "graphics/kao/wigglytuff_168CAFC_2A4.bin"
sPortraitsWigglytuff:
kao_portrait sWigglytuffNormalPal, sWigglytuffNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
