.global gKaoWobbuffet
gKaoWobbuffet:
kao_siro sPortraitsWobbuffet
sWobbuffetNormalPal:
.incbin "graphics/kao/wobbuffet_16A5FA0_40.bin"
sWobbuffetNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/wobbuffet_16A5FE5_223.bin"
sWobbuffetHappyPal:
.incbin "graphics/kao/wobbuffet_16A6208_40.bin"
sWobbuffetHappyGfx:
.string "AT4PX"
.incbin "graphics/kao/wobbuffet_16A624D_2A3.bin"
sPortraitsWobbuffet:
kao_portrait sWobbuffetNormalPal, sWobbuffetNormalGfx
kao_portrait sWobbuffetHappyPal, sWobbuffetHappyGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
