.global gKaoWynaut
gKaoWynaut:
kao_siro sPortraitsWynaut
sWynautNormalPal:
.incbin "graphics/kao/wynaut_16B9C8C_40.bin"
sWynautNormalGfx:
.incbin "graphics/kao/wynaut_16B9CCC_2BC.bin"
sPortraitsWynaut:
kao_portrait sWynautNormalPal, sWynautNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
