.global gKaoXatu
gKaoXatu:
kao_siro sPortraitsXatu
sXatuNormalPal:
.incbin "graphics/kao/xatu_16A5664_40.bin"
sXatuNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/xatu_16A56A9_277.bin"
sPortraitsXatu:
kao_portrait sXatuNormalPal, sXatuNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
