.global gKaoZapdos
gKaoZapdos:
kao_siro sPortraitsZapdos
sZapdosNormalPal:
.incbin "graphics/kao/zapdos_169DAC0_40.bin"
sZapdosNormalGfx:
.string "AT4PX"
.incbin "graphics/kao/zapdos_169DB05_297.bin"
sPortraitsZapdos:
kao_portrait sZapdosNormalPal, sZapdosNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
