#!/usr/bin/env python3
"""Generate RescueTemple RuntimeConfig header snapshot from include/runtime.h.

Keeps C Patches field order/IDs locked to the decomp struct so the editor cannot drift.
UI metadata (labels/groups) stays in RuntimeConfigSchema.cs and is merged at runtime.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

STRUCT_RE = re.compile(
    r"typedef\s+struct\s*\{(.*?)\}\s*RuntimeConfig\s*;",
    re.DOTALL,
)
FIELD_RE = re.compile(
    r"^\s*u8\s+([A-Za-z_][A-Za-z0-9_]*)\s*;\s*(?:/\*\s*(.*?)\s*\*/)?\s*$"
)


def clean_comment(text: str) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    return text.replace("\\", "\\\\").replace('"', '\\"')


def parse_fields(header_text: str) -> list[tuple[str, str]]:
    match = STRUCT_RE.search(header_text)
    if not match:
        raise SystemExit("Could not find typedef struct RuntimeConfig in include/runtime.h")

    fields: list[tuple[str, str]] = []
    pending: list[str] = []
    for raw in match.group(1).splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("/*") or (line.startswith("*") and not line.startswith("*/")):
            text = line
            if text.startswith("/*"):
                text = text[2:]
            if text.startswith("*"):
                text = text[1:]
            if text.endswith("*/"):
                text = text[:-2]
            text = text.strip()
            if text:
                pending.append(text)
            continue

        field = FIELD_RE.match(raw.rstrip("\r"))
        if not field:
            pending.clear()
            continue

        ident = field.group(1)
        inline = (field.group(2) or "").strip()
        block = " ".join(pending).strip()
        pending.clear()
        comment = inline or block
        fields.append((ident, clean_comment(comment)))

    if not fields:
        raise SystemExit("RuntimeConfig struct contained no u8 fields")
    return fields


def generate_csharp(fields: list[tuple[str, str]]) -> str:
    lines = [
        "// <auto-generated />",
        "// Generated by tools/gen_runtime_config_schema.py from include/runtime.h",
        "// Do not edit manually — re-run the generator after changing RuntimeConfig.",
        "namespace RescueEditor.Core;",
        "",
        "/// <summary>Snapshot of <c>RuntimeConfig</c> member order from <c>include/runtime.h</c>.</summary>",
        "public static class RuntimeConfigHeaderSnapshot",
        "{",
        '    public const string RelativePath = "include/runtime.h";',
        "",
        "    public static readonly RuntimeConfigHeaderField[] Fields =",
        "    [",
    ]
    for index, (ident, comment) in enumerate(fields):
        lines.append(
            f'        new("{ident}", "{comment}", {index}),'
        )
    lines.extend(
        [
            "    ];",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--header",
        type=Path,
        default=root / "include" / "runtime.h",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=root
        / "RescueEditor/src/RescueEditor.Core/Generated/RuntimeConfigHeaderSnapshot.g.cs",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the generated snapshot would change (no write).",
    )
    args = parser.parse_args()

    if not args.header.is_file():
        raise SystemExit(f"missing {args.header}")

    fields = parse_fields(args.header.read_text(encoding="utf-8", errors="replace"))
    text = generate_csharp(fields)

    if args.check:
        if not args.output.is_file():
            raise SystemExit(f"missing snapshot {args.output} — run without --check")
        existing = args.output.read_text(encoding="utf-8")
        if existing != text:
            raise SystemExit(
                "RuntimeConfigHeaderSnapshot.g.cs is out of date with include/runtime.h.\n"
                "Run: python3 tools/gen_runtime_config_schema.py"
            )
        print(f"OK: {args.output} matches {args.header} ({len(fields)} fields)")
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"Wrote {args.output} ({len(fields)} fields)")


if __name__ == "__main__":
    main()
