<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS9057</NoWarn>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\rescuetemple_logo.ico</ApplicationIcon>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyName>RescueTemple</AssemblyName>
    <Product>RescueTemple</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RescueEditor.Core\RescueEditor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\rescuetemple_logo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../../charmap.txt" Link="charmap.txt"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../tools/agbplay/**/*" Link="tools/agbplay/%(RecursiveDir)%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
