#include "global.h"
#include "custom_title_backgrounds.h"

/*
 * Custom title-screen backgrounds from graphics/title_screen_backgrounds/.
 * Generated by convert_title_backgrounds.py (*.at4pn + *.pal).
 * File names must stay sorted for OpenFile binary search.
 */

const u8 gCustomTitleBg0[] = INCBIN_U8("graphics/title_screen_backgrounds/title_01.at4pn");
const u8 gCustomTitleBg0Pal[] = INCBIN_U8("graphics/title_screen_backgrounds/title_01.pal");
const u8 gCustomTitleBg1[] = INCBIN_U8("graphics/title_screen_backgrounds/title_02.at4pn");
const u8 gCustomTitleBg1Pal[] = INCBIN_U8("graphics/title_screen_backgrounds/title_02.pal");
const u8 gCustomTitleBg2[] = INCBIN_U8("graphics/title_screen_backgrounds/title_03.at4pn");
const u8 gCustomTitleBg2Pal[] = INCBIN_U8("graphics/title_screen_backgrounds/title_03.pal");
const u8 gCustomTitleBg3[] = INCBIN_U8("graphics/title_screen_backgrounds/title_04.at4pn");
const u8 gCustomTitleBg3Pal[] = INCBIN_U8("graphics/title_screen_backgrounds/title_04.pal");
const u8 gCustomTitleBg4[] = INCBIN_U8("graphics/title_screen_backgrounds/title_05.at4pn");
const u8 gCustomTitleBg4Pal[] = INCBIN_U8("graphics/title_screen_backgrounds/title_05.pal");
const u8 gCustomTitleBg5[] = INCBIN_U8("graphics/title_screen_backgrounds/title_06.at4pn");
const u8 gCustomTitleBg5Pal[] = INCBIN_U8("graphics/title_screen_backgrounds/title_06.pal");

#define CUSTOM_TITLE_BG_FILES_COUNT (CUSTOM_TITLE_BG_COUNT * 2)

const File gCustomTitleBgFiles[CUSTOM_TITLE_BG_FILES_COUNT] = {
    [0] = { "ctitle0", gCustomTitleBg0 },
    [1] = { "ctitle0p", gCustomTitleBg0Pal },
    [2] = { "ctitle1", gCustomTitleBg1 },
    [3] = { "ctitle1p", gCustomTitleBg1Pal },
    [4] = { "ctitle2", gCustomTitleBg2 },
    [5] = { "ctitle2p", gCustomTitleBg2Pal },
    [6] = { "ctitle3", gCustomTitleBg3 },
    [7] = { "ctitle3p", gCustomTitleBg3Pal },
    [8] = { "ctitle4", gCustomTitleBg4 },
    [9] = { "ctitle4p", gCustomTitleBg4Pal },
    [10] = { "ctitle5", gCustomTitleBg5 },
    [11] = { "ctitle5p", gCustomTitleBg5Pal },
};

const FileArchive gCustomTitleBgArchive = {
    .magic = "pksdir0",
    .count = CUSTOM_TITLE_BG_FILES_COUNT,
    .entries = gCustomTitleBgFiles,
};
